// DYEFIELD — shared menu art: the in-game icons (the HUD's special / sub glyphs), crew marks, and the baked
// thumbnails in ./assets (map renders and kit cut-outs — generated by ./assets/build_thumbs.py from
// art/renders; Vite fingerprints them into dist/assets).

export const MAP_THUMBS: Readonly<Record<string, string>> = {
  pier18: new URL('./assets/map_pier18.webp', import.meta.url).href,
  lockwell: new URL('./assets/map_lockwell.webp', import.meta.url).href,
  cinder: new URL('./assets/map_cinder.webp', import.meta.url).href,
};

export const KIT_ICONS: Readonly<Record<string, string>> = {
  'mist-rasp': new URL('./assets/kit_mist-rasp.webp', import.meta.url).href,
  'sheet-drum': new URL('./assets/kit_sheet-drum.webp', import.meta.url).href,
  'needle-glint': new URL('./assets/kit_needle-glint.webp', import.meta.url).href,
  'pop-well': new URL('./assets/kit_pop-well.webp', import.meta.url).href,
};

/** the HUD's special / sub icons (hud.ts draws the same glyphs in the match) */
export const SVG: Readonly<Record<string, string>> = {
  cloudburst: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6.6 14.6a3.6 3.6 0 0 1 .3-7.2 5 5 0 0 1 9.4-1.3 4.1 4.1 0 0 1 1.3 8.5z" fill="#fff8ec" stroke="#14203a" stroke-width="1.6" stroke-linejoin="round"/>'
    + '<path d="M8.2 17.4l-1 2.8M12.2 17.4l-1 2.8M16.2 17.4l-1 2.8" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/></svg>',
  wellspring: '<svg viewBox="0 0 24 24" aria-hidden="true"><ellipse cx="12" cy="18.2" rx="9.4" ry="3.4" fill="none" stroke="currentColor" stroke-width="2.4"/>'
    + '<ellipse cx="12" cy="18.2" rx="4.6" ry="1.6" fill="none" stroke="#14203a" stroke-width="1.6"/>'
    + '<path d="M12 14.6V3.6M7.8 7.8L12 3.6l4.2 4.2" fill="none" stroke="#14203a" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  'jelly-charge': '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.6 16.2c0-5.2 3.8-9.4 8.4-9.4s8.4 4.2 8.4 9.4c0 1.8-3.8 3.2-8.4 3.2s-8.4-1.4-8.4-3.2z" fill="currentColor" stroke="#14203a" stroke-width="1.7"/>'
    + '<ellipse cx="12" cy="15.4" rx="3.2" ry="2.2" fill="#fff8ec" opacity=".85"/><path d="M7.6 11c1-1.5 2.4-2.2 3.8-2.3" stroke="#fff8ec" stroke-width="1.7" stroke-linecap="round" fill="none"/></svg>',
  dice: '<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="10" y="10" width="44" height="44" rx="11" fill="#fff8ec" stroke="#14203a" stroke-width="4" transform="rotate(-8 32 32)"/>'
    + '<g fill="#14203a" transform="rotate(-8 32 32)"><circle cx="22" cy="22" r="4.2"/><circle cx="42" cy="22" r="4.2"/><circle cx="32" cy="32" r="4.2"/><circle cx="22" cy="42" r="4.2"/><circle cx="42" cy="42" r="4.2"/></g></svg>',
  gamepad: '<svg viewBox="0 0 32 20" aria-hidden="true"><path d="M8 2h16c3.6 0 6 3.4 6.8 8.6.6 4.2-1 7.4-3.8 7.4-2 0-3.2-1.6-4.6-3.6H9.6C8.2 16.4 7 18 5 18c-2.8 0-4.4-3.2-3.8-7.4C2 5.4 4.4 2 8 2z" fill="currentColor"/>'
    + '<path d="M8.6 6.4v6M5.6 9.4h6" stroke="#14203a" stroke-width="2.2" stroke-linecap="round"/><circle cx="22.4" cy="7.6" r="1.7" fill="#14203a"/><circle cx="25.6" cy="10.8" r="1.7" fill="#14203a"/></svg>',
};

/** the role badge line of a kit tile (weapons.json role, e.g. SHOOTER) */
export function roleLabel(role: string | undefined): string {
  return (role ?? '').toUpperCase();
}
