// Generates _spec/CATALOG.md from the data (src/data/catalog.ts, rarity.ts, shapes.ts, materials.ts, palette.ts, src/core/merge.ts) so the
// owner can review the roster at a glance.
// Plain node:   node _harness/gen_catalog_doc.ts          (deterministic: no clock, same data => same file)
// Do not edit _spec/CATALOG.md by hand; edit the catalog and run this again. probe_catalog.ts imports renderCatalogDoc() and FAILS when the
// committed file differs from what the data generates (a stale doc cannot ship silently).
// Only src/core and src/data are read: colours come from the palette contract (src/data/palette.ts), never from the render lane's code.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { CATALOG, LANES, speciesTemplateGenome, DEFAULT_LOOK_BANDS, SIGNATURE_BIAS, PATTERN_SPECKLE_FLOOR } from '../src/data/catalog.ts';
import type { SpeciesDef } from '../src/data/catalog.ts';
import { shapeBounds, shapeDistance, shapeVolumeRatio } from '../src/data/shapes.ts';
import { MATERIAL_FAMILIES, MATERIAL_FAMILY_IDS, feelOf } from '../src/data/materials.ts';
import { TIERS, TIER_NAMES, TIER_ODDS_PERCENT, TIER_SPECIES_COUNTS, TIER_STYLE, tierIndex } from '../src/core/rarity.ts';
import { MERGE_COST, MERGE_TIER_UP } from '../src/core/merge.ts';
import type { Genome } from '../src/core/genome.ts';
import { bodyLinear, coreLinear, linearToOklab, labDistance as dE, linearToHex as hex } from '../src/data/palette.ts';

const here = dirname(fileURLToPath(import.meta.url));
/** Where the generated file lives. */
export const CATALOG_DOC_PATH = resolve(here, '../_spec/CATALOG.md');
const centre = (d: SpeciesDef): Genome => speciesTemplateGenome(d.id);
const swatch = (h: string): string => `<span style="color:${h}">&#9632;</span> \`${h}\``;
const esc = (s: string): string => s.replace(/\|/g, '\\|');
const f2 = (x: number): string => x.toFixed(2);

const familyName = (id: string): string => MATERIAL_FAMILIES[id as keyof typeof MATERIAL_FAMILIES].name;

/** The full text of _spec/CATALOG.md as the data generates it (pure: no file access, no clock). */
export function renderCatalogDoc(): string {
  const pal = CATALOG.map((d) => ({ body: bodyLinear(centre(d)), core: coreLinear(centre(d)) }));
  const labs = pal.map((p) => linearToOklab(p.body));
  const out: string[] = [];
  out.push('# WOBBLEHOARD catalog: the 50 squishies');
  out.push('');
  out.push('Generated by `node _harness/gen_catalog_doc.ts` from `src/data/catalog.ts`. **Do not edit by hand.** Names, blurbs, palettes and shapes are invented for this game (see the originality gate in `_harness/probe_catalog.ts`).');
  out.push('');
  out.push('`idx` is the stable index stored in share strings: **append-only forever** (never reorder, rename the id of, or reuse an entry). Colours are the species centre colour from the palette contract `src/data/palette.ts` (the same formulas `genomePalette` in the render lane draws with); each instance varies by a few degrees of hue and a few percent of the other numbers.');
  out.push('');

  out.push('## Rarity at a glance');
  out.push('');
  out.push('| Tier | Species | Public odds per capsule | Odds per species | Merge tier-up chance | UI gem | Inner-light tell colour |');
  out.push('|---|---|---|---|---|---|---|');
  TIERS.forEach((t, i) => {
    const st = TIER_STYLE[t];
    out.push(`| ${TIER_NAMES[t]} | ${TIER_SPECIES_COUNTS[i]} | ${TIER_ODDS_PERCENT[i]}% | ${(TIER_ODDS_PERCENT[i] / TIER_SPECIES_COUNTS[i]).toFixed(2)}% | ${i < 5 ? Math.round(MERGE_TIER_UP[i] * 100) + '%' : 'cannot merge'} | ${st.gem} (${st.gemPoints || 'round'}) | ${swatch(st.tellHex)} |`);
  });
  out.push('');
  out.push(`Merge cost is **${MERGE_COST}** of the same species (\`MERGE_COST\` in \`src/core/merge.ts\`).`);
  out.push('');

  out.push('## Family lanes and the DESIGN 5.2 grid');
  out.push('');
  out.push('Each lane is one column (A to F) of the family-by-tier grid in `_spec/DESIGN.md` 5.2: an everyday family and a signature family, and the signature family always sits higher in tier. Counts are species per tier.');
  out.push('');
  out.push('| Lane | Everyday family | Signature family | Common | Uncommon | Rare | Epic | Legendary | Mythic | Total |');
  out.push('|---|---|---|---|---|---|---|---|---|---|');
  for (const l of LANES) {
    const row = TIERS.map((t) => CATALOG.filter((d) => d.lane === l.id && d.tier === t).length);
    out.push(`| ${l.letter} ${l.name} | ${familyName(l.everyday)} | ${familyName(l.signature)} | ${row.join(' | ')} | ${row.reduce((a, b) => a + b, 0)} |`);
  }
  out.push('');
  out.push('| Family | Touch feel (one line) | Clearest body (translucency cap) | Species | Tiers it appears in |');
  out.push('|---|---|---|---|---|');
  for (const f of MATERIAL_FAMILY_IDS) {
    const sp = CATALOG.filter((d) => d.family === f);
    const pl = MATERIAL_FAMILIES[f].planned, lb = MATERIAL_FAMILIES[f].lookBounds;
    out.push(`| ${familyName(f)} (\`${f}\`) | ${esc(MATERIAL_FAMILIES[f].blurb)}${pl ? ` *Planned, not built yet: ${esc(pl.feature)}.*` : ''} | ${lb ? `at most ${f2(lb.translucencyMax)}` : 'can be clear (no cap)'} | ${sp.map((d) => d.name).join(', ')} | ${[...new Set(sp.map((d) => TIER_NAMES[d.tier]))].join(', ')} |`);
  }
  out.push('');
  const capped = MATERIAL_FAMILY_IDS.filter((f) => MATERIAL_FAMILIES[f].lookBounds);
  out.push(`**Opaque families keep an opaque body.** \`resolveMaterial\` (\`src/data/materials.ts\`) passes the genome's translucency, gloss, core glow and glitter through, then caps translucency for the families that are opaque in the hand (\`lookBounds\`): ${capped.map((f) => `${familyName(f)} ${f2(MATERIAL_FAMILIES[f].lookBounds!.translucencyMax)} (${esc(MATERIAL_FAMILIES[f].lookBounds!.why)})`).join('; ')}. Every species of these families sits under its cap with its whole cosmetic band (no instance is ever clipped) and shows its tier through core glow, glitter and gloss instead of a see-through body.`);
  out.push('');

  out.push('## The roster');
  out.push('');
  out.push('| idx | Name | Tier | Family (lane) | Touch | Silhouette | Body | Core | Blurb |');
  out.push('|---|---|---|---|---|---|---|---|---|');
  CATALOG.forEach((d, i) => {
    out.push(`| ${d.idx} | **${d.name}** | ${TIER_NAMES[d.tier]} | ${familyName(d.family)} (${d.lane}) | ${d.signature} | ${esc(d.silhouette)} | ${swatch(hex(pal[i].body))} | ${swatch(hex(pal[i].core))} | ${esc(d.blurb)} |`);
  });
  out.push('');

  for (const t of TIERS) {
    out.push(`### ${TIER_NAMES[t]} (${TIER_SPECIES_COUNTS[tierIndex(t)]})`);
    out.push('');
    out.push('| idx | Name | Family | Look numbers (core glow / glitter / gloss / translucency / pattern / eyes / size) | Shape (features / volume / height) | Closest silhouette | Closest colour |');
    out.push('|---|---|---|---|---|---|---|');
    for (const d of CATALOG.filter((x) => x.tier === t)) {
      const i = d.idx;
      let bs = 9, bn = '', bc = 9, cn = '';
      for (const o of CATALOG) { if (o.idx === i) continue; const sd = shapeDistance(d.shape, o.shape); if (sd < bs) { bs = sd; bn = o.name; } const cd = dE(labs[i], labs[o.idx]); if (cd < bc) { bc = cd; cn = o.name; } }
      const b = shapeBounds(d.shape);
      out.push(`| ${d.idx} | ${d.name} | ${familyName(d.family)} | ${f2(d.look.coreGlow)} / ${f2(d.look.glitter)} / ${f2(d.look.gloss)} / ${f2(d.look.translucency)}${MATERIAL_FAMILIES[d.family].lookBounds ? ` (cap ${f2(MATERIAL_FAMILIES[d.family].lookBounds!.translucencyMax)})` : ''} / ${d.look.pattern} ${d.look.pattern === 'plain' ? '' : f2(d.look.speckle)} / ${d.look.eyeStyle} / ${f2(d.look.size)} | ${d.shape.features.length + (d.shape.swirl ? 1 : 0)} / ${f2(shapeVolumeRatio(d.shape))} / ${f2(b.height)} | ${bn} ${f2(bs)} | ${cn} ${bc.toFixed(3)} |`);
    }
    out.push('');
  }

  out.push('## Feel of each family (physics scores 0 to 1, from `src/data/materials.ts`)');
  out.push('');
  out.push('| Family | firm | squashy | slow rise | holds dent | bouncy | stretchy | tacky | sloshy | snappy | rate stiff |');
  out.push('|---|---|---|---|---|---|---|---|---|---|---|');
  for (const f of MATERIAL_FAMILY_IDS) {
    const v = feelOf(MATERIAL_FAMILIES[f].physics);
    out.push(`| ${familyName(f)} | ${[v.firm, v.squashy, v.slowRise, v.holdsDent, v.bouncy, v.stretchy, v.tacky, v.sloshy, v.snappy, v.rateStiff].map(f2).join(' | ')} |`);
  }
  out.push('');
  const planned = MATERIAL_FAMILY_IDS.filter((f) => MATERIAL_FAMILIES[f].planned);
  if (planned.length) {
    out.push(`Scores are the specified numbers. Planned, not built yet (no blurb may promise it until it ships): ${planned.map((f) => `${familyName(f)}: ${MATERIAL_FAMILIES[f].planned!.feature}`).join('; ')}.`);
    out.push('');
  }
  out.push('## Known sources of variation inside a species');
  out.push('');
  const B = DEFAULT_LOOK_BANDS, n = (x: number): string => String(+x.toFixed(3));
  const shifts = (['poke', 'squeeze', 'pull'] as const).map((k) => Object.entries(SIGNATURE_BIAS[k]).map(([f, v]) => `${k} ${f} +${n(v as number)}`).join('')).join(', ');
  out.push(`\`speciesBaseGenome(species, seed)\` rolls (triangular, default bands) hue +-${n(B.hue)} degrees, chroma +-${n(B.chroma)}, lightness +-${n(B.lightness)}, core hue +-${n(B.coreHue)} degrees, core glow +-${n(B.coreGlow)}, translucency +-${n(B.translucency)}, gloss +-${n(B.gloss)}, firmness +-${n(B.firmness)}, bounce +-${n(B.bounce)}, stretch +-${n(B.stretch)} (plus a centre shift for the signature touch: ${shifts}), size +-${n(B.size)}, glitter +-${n(B.glitter)}, speckle +-${n(B.speckle)} (never below ${PATTERN_SPECKLE_FLOOR} on a patterned species, so a Rare-and-up instance always shows its layer), eye spacing +-${n(B.eyeSpacing)}, eye size +-${n(B.eyeSize)}, eye height +-${n(B.eyeHeight)}. A zero glitter or speckle stays zero. Pattern and eye style never vary. Two Plumpets are recognisably the same species, never identical.`);
  out.push('');
  const overrides = CATALOG.filter((d) => (Object.keys(B) as Array<keyof typeof B>).some((k) => d.bands[k] !== B[k]));
  if (overrides.length) {
    out.push(`Per-species band overrides: ${overrides.map((d) => `${d.name} (${(Object.keys(B) as Array<keyof typeof B>).filter((k) => d.bands[k] !== B[k]).map((k) => `${k} +-${n(d.bands[k])}`).join(', ')})`).join('; ')}.`);
    out.push('');
  }

  return out.join('\n') + '\n';
}

if (import.meta.main) {
  const text = renderCatalogDoc();
  writeFileSync(CATALOG_DOC_PATH, text);
  console.log(`wrote ${CATALOG_DOC_PATH} (${text.split('\n').length - 1} lines, ${CATALOG.length} species)`);
}
