// Generates _spec/CATALOG.md from the data (src/data/catalog.ts, rarity.ts, shapes.ts) so the owner can review the roster at a glance.
// Plain node:   node _harness/gen_catalog_doc.ts          (deterministic: no clock, same data => same file)
// Do not edit _spec/CATALOG.md by hand; edit the catalog and run this again.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { CATALOG, LANES, speciesTemplateGenome } from '../src/data/catalog.ts';
import type { SpeciesDef } from '../src/data/catalog.ts';
import { shapeBounds, shapeDistance, shapeVolumeRatio } from '../src/data/shapes.ts';
import { MATERIAL_FAMILIES, MATERIAL_FAMILY_IDS, feelOf } from '../src/data/materials.ts';
import { TIERS, TIER_NAMES, TIER_ODDS_PERCENT, TIER_SPECIES_COUNTS, TIER_STYLE, tierIndex } from '../src/core/rarity.ts';
import { MERGE_COST, MERGE_TIER_UP } from '../src/core/merge.ts';
import type { Genome } from '../src/core/genome.ts';
import { genomePalette, linearToSrgb } from '../src/render/oklch.ts';

const here = dirname(fileURLToPath(import.meta.url));
const hex = (lin: readonly number[]): string => '#' + lin.map((v) => Math.round(255 * Math.min(1, Math.max(0, linearToSrgb(v)))).toString(16).padStart(2, '0')).join('');
const toOklab = (lin: readonly number[]): number[] => {
  const [r, g, b] = lin;
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b), m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b), s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s, 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s, 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s];
};
const dE = (a: number[], b: number[]): number => Math.hypot(a[0] - b[0], a[1] - b[1], a[2] - b[2]);
const centre = (d: SpeciesDef): Genome => speciesTemplateGenome(d.id);
const swatch = (h: string): string => `<span style="color:${h}">&#9632;</span> \`${h}\``;
const esc = (s: string): string => s.replace(/\|/g, '\\|');
const f2 = (x: number): string => x.toFixed(2);

const pal = CATALOG.map((d) => genomePalette(centre(d)));
const labs = pal.map((p) => toOklab(p.body));
const familyName = (id: string): string => MATERIAL_FAMILIES[id as keyof typeof MATERIAL_FAMILIES].name;

const out: string[] = [];
out.push('# WOBBLEHOARD catalog: the 50 squishies');
out.push('');
out.push('Generated by `node _harness/gen_catalog_doc.ts` from `src/data/catalog.ts`. **Do not edit by hand.** Names, blurbs, palettes and shapes are invented for this game (see the originality gate in `_harness/probe_catalog.ts`).');
out.push('');
out.push('`idx` is the stable index stored in share strings: **append-only forever** (never reorder, rename the id of, or reuse an entry). Colours are the species centre colour as the renderer draws it (`genomePalette`); each instance varies by a few degrees of hue and a few percent of the other numbers.');
out.push('');

out.push('## Rarity at a glance');
out.push('');
out.push('| Tier | Species | Public odds per capsule | Odds per species | Merge tier-up chance | UI gem | Inner-light tell colour |');
out.push('|---|---|---|---|---|---|---|');
TIERS.forEach((t, i) => {
  const st = TIER_STYLE[t];
  out.push(`| ${TIER_NAMES[t]} | ${TIER_SPECIES_COUNTS[i]} | ${TIER_ODDS_PERCENT[i]}% | ${(TIER_ODDS_PERCENT[i] / TIER_SPECIES_COUNTS[i]).toFixed(2)}% | ${i < 5 ? Math.round(MERGE_TIER_UP[i] * 100) + '%' : 'cannot merge'} | ${st.gem} (${st.gemPoints || 'round'}) | ${swatch(st.tellHex)} |`);
});
out.push('');
out.push(`Merge cost is **${MERGE_COST}** of the same species (\`MERGE_COST\` in \`src/core/merge.ts\`).`);
out.push('');

out.push('## Family lanes and the DESIGN 5.2 grid');
out.push('');
out.push('Each lane is one column (A to F) of the family-by-tier grid in `_spec/DESIGN.md` 5.2: an everyday family and a signature family, and the signature family always sits higher in tier. Counts are species per tier.');
out.push('');
out.push('| Lane | Everyday family | Signature family | Common | Uncommon | Rare | Epic | Legendary | Mythic | Total |');
out.push('|---|---|---|---|---|---|---|---|---|---|');
for (const l of LANES) {
  const row = TIERS.map((t) => CATALOG.filter((d) => d.lane === l.id && d.tier === t).length);
  out.push(`| ${l.letter} ${l.name} | ${familyName(l.everyday)} | ${familyName(l.signature)} | ${row.join(' | ')} | ${row.reduce((a, b) => a + b, 0)} |`);
}
out.push('');
out.push('| Family | Touch feel (one line) | Species | Tiers it appears in |');
out.push('|---|---|---|---|');
for (const f of MATERIAL_FAMILY_IDS) {
  const sp = CATALOG.filter((d) => d.family === f);
  out.push(`| ${familyName(f)} (\`${f}\`) | ${esc(MATERIAL_FAMILIES[f].blurb)} | ${sp.map((d) => d.name).join(', ')} | ${[...new Set(sp.map((d) => TIER_NAMES[d.tier]))].join(', ')} |`);
}
out.push('');

out.push('## The roster');
out.push('');
out.push('| idx | Name | Tier | Family (lane) | Touch | Silhouette | Body | Core | Blurb |');
out.push('|---|---|---|---|---|---|---|---|---|');
CATALOG.forEach((d, i) => {
  out.push(`| ${d.idx} | **${d.name}** | ${TIER_NAMES[d.tier]} | ${familyName(d.family)} (${d.lane}) | ${d.signature} | ${esc(d.silhouette)} | ${swatch(hex(pal[i].body))} | ${swatch(hex(pal[i].core))} | ${esc(d.blurb)} |`);
});
out.push('');

for (const t of TIERS) {
  out.push(`### ${TIER_NAMES[t]} (${TIER_SPECIES_COUNTS[tierIndex(t)]})`);
  out.push('');
  out.push('| idx | Name | Family | Look numbers (core glow / glitter / translucency / pattern / eyes / size) | Shape (features / volume / height) | Closest silhouette | Closest colour |');
  out.push('|---|---|---|---|---|---|---|');
  for (const d of CATALOG.filter((x) => x.tier === t)) {
    const i = d.idx;
    let bs = 9, bn = '', bc = 9, cn = '';
    for (const o of CATALOG) { if (o.idx === i) continue; const sd = shapeDistance(d.shape, o.shape); if (sd < bs) { bs = sd; bn = o.name; } const cd = dE(labs[i], labs[o.idx]); if (cd < bc) { bc = cd; cn = o.name; } }
    const b = shapeBounds(d.shape);
    out.push(`| ${d.idx} | ${d.name} | ${familyName(d.family)} | ${f2(d.look.coreGlow)} / ${f2(d.look.glitter)} / ${f2(d.look.translucency)} / ${d.look.pattern} ${d.look.pattern === 'plain' ? '' : f2(d.look.speckle)} / ${d.look.eyeStyle} / ${f2(d.look.size)} | ${d.shape.features.length + (d.shape.swirl ? 1 : 0)} / ${f2(shapeVolumeRatio(d.shape))} / ${f2(b.height)} | ${bn} ${f2(bs)} | ${cn} ${bc.toFixed(3)} |`);
  }
  out.push('');
}

out.push('## Feel of each family (physics scores 0 to 1, from `src/data/materials.ts`)');
out.push('');
out.push('| Family | firm | squashy | slow rise | holds dent | bouncy | stretchy | tacky | sloshy | snappy | rate stiff |');
out.push('|---|---|---|---|---|---|---|---|---|---|---|');
for (const f of MATERIAL_FAMILY_IDS) {
  const v = feelOf(MATERIAL_FAMILIES[f].physics);
  out.push(`| ${familyName(f)} | ${[v.firm, v.squashy, v.slowRise, v.holdsDent, v.bouncy, v.stretchy, v.tacky, v.sloshy, v.snappy, v.rateStiff].map(f2).join(' | ')} |`);
}
out.push('');
out.push('## Known sources of variation inside a species');
out.push('');
out.push('`speciesBaseGenome(species, seed)` rolls hue +-4 degrees, chroma +-0.04, lightness +-0.035, core hue +-8 degrees, core glow, translucency and gloss +-0.06, firmness / bounce / stretch +-0.08 (plus a +0.04 centre shift for the signature touch), size +-0.07, glitter +-0.08, speckle +-0.12, eye spacing / size / height +-0.06. Pattern and eye style never vary. Two Plumpets are recognisably the same species, never identical.');
out.push('');

const path = resolve(here, '../_spec/CATALOG.md');
writeFileSync(path, out.join('\n') + '\n');
console.log(`wrote ${path} (${out.length} lines, ${CATALOG.length} species)`);
