// VALE — regenerate content/store.json from content/skins/*.json + content/fighters/*.json.
//
//   node tools/gen_store.ts            write content/store.json
//   node tools/gen_store.ts --check    exit 1 if content/store.json is out of date (writes nothing)
//   flags: --content <dir>
//
// One offer per NON-base skin (sku `sku_<skin_id>`). Prices are Candles by tier (modes_economy.md §8,
// with `legend` set to 3,600 for this slice, which has no premium currency). Shelves: Featured (hero),
// New (row), then one row per fighter class. starterOwnership = every base skin; starterWallet = 300
// Candles. Run it again whenever a skin file is added or changed; the output is deterministic.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const flag = (n: string): boolean => args.includes(n);
const opt = (n: string, d: string): string => { const i = args.indexOf(n); return i >= 0 && args[i + 1] ? args[i + 1] : d; };
const CONTENT = resolve(opt('--content', join(ROOT, 'content')));

const CURRENCY = 'candles';
const PRICE: Record<string, number> = { standard: 900, deluxe: 2250, legend: 3600 };
const TIER_ORDER = ['standard', 'deluxe', 'legend'];
const STARTER_CANDLES = 300;
/** skins that carry the "new" badge and fill the New row (only those that exist are used) */
const NEW_SKINS = ['ardit_first_bell', 'ilsheta_first_bell', 'kemdo_long_evening', 'nurrow_noon_fair', 'tunlan_lamplit', 'ulkro_highrim'];
/** the hero shelf (3 to 4 skus; only those that exist are used) */
const FEATURED = ['ardit_first_bell', 'ilsheta_first_bell', 'kemdo_long_evening', 'vashil_first_bell'];
const CLASS_ROWS: [string, string][] = [
  ['class_plinth', 'Plinths'], ['class_breaker', 'Breakers'], ['class_striker', 'Strikers'],
  ['class_slinger', 'Slingers'], ['class_caster', 'Casters'], ['class_tender', 'Tenders'],
];

interface Skin { id: string; fighter: string; tier: string }
const readJson = (p: string): unknown => JSON.parse(readFileSync(p, 'utf8'));

const fighterClass = new Map<string, string>();
for (const f of readdirSync(join(CONTENT, 'fighters')).filter((n) => n.endsWith('.json')).sort()) {
  const rec = readJson(join(CONTENT, 'fighters', f)) as { id: string; class: string };
  fighterClass.set(rec.id, rec.class);
}
const skins: Skin[] = [];
const skinFiles = readdirSync(join(CONTENT, 'skins')).filter((n) => n.endsWith('.json')).sort();
for (const f of skinFiles) {
  const v = readJson(join(CONTENT, 'skins', f)) as Skin[] | { skins: Skin[] };
  skins.push(...(Array.isArray(v) ? v : v.skins));
}

const base = skins.filter((s) => s.tier === 'base');
const sold = skins.filter((s) => s.tier !== 'base')
  .sort((a, b) => a.fighter.localeCompare(b.fighter) || TIER_ORDER.indexOf(a.tier) - TIER_ORDER.indexOf(b.tier));
for (const s of sold) if (!(s.tier in PRICE)) throw new Error(`skin ${s.id}: no price for tier "${s.tier}"`);
const skuOf = (skinId: string): string => `sku_${skinId}`;
const have = new Set(sold.map((s) => s.id));
const isNew = new Set(NEW_SKINS.filter((id) => have.has(id)));

const offers = sold.map((s) => ({
  sku: skuOf(s.id), kind: 'skin', ref: s.id, price: { currency: CURRENCY, amount: PRICE[s.tier] },
  ...(isNew.has(s.id) ? { badge: 'new' } : {}),
}));
const shelves: { id: string; name: string; skus: string[]; layout: string }[] = [
  { id: 'featured', name: 'Featured', layout: 'hero', skus: FEATURED.filter((id) => have.has(id)).slice(0, 4).map(skuOf) },
  { id: 'new', name: 'New', layout: 'row', skus: NEW_SKINS.filter((id) => have.has(id)).map(skuOf) },
];
for (const [cls, name] of CLASS_ROWS) {
  const ids = sold.filter((s) => fighterClass.get(s.fighter) === cls).map((s) => skuOf(s.id));
  if (ids.length) shelves.push({ id: `by_${cls.replace(/^class_/, '')}`, name, layout: 'row', skus: ids });
}
const unclassed = sold.filter((s) => !CLASS_ROWS.some(([c]) => c === fighterClass.get(s.fighter))).map((s) => skuOf(s.id));
if (unclassed.length) shelves.push({ id: 'by_other', name: 'More', layout: 'row', skus: unclassed });

const line = (v: unknown): string => JSON.stringify(v);
const text = `{
  "$comment": "VALE store (CONTRACT §4 StoreDef). Generated by tools/gen_store.ts from content/skins and content/fighters; re-run it when a skin is added. Scope note: this slice has NO premium currency, so the Prisms currency and the 1,350 Prisms legend pricing in _design/sections/modes_economy.md §8 are out of scope; legend skins (none yet) would cost 3,600 Candles. Prices: standard 900, deluxe 2,250.",
  "currencies": [
    ${line({ id: CURRENCY, name: 'Candles', desc: 'Earned by playing matches. Spend them on skins.', icon: 'assets/ui/icons/currency/candles.svg', earnedOnly: true })}
  ],
  "offers": [
${offers.map((o) => `    ${line(o)}`).join(',\n')}
  ],
  "shelves": [
${shelves.map((s) => `    ${line(s)}`).join(',\n')}
  ],
  "starterOwnership": ${line(base.map((s) => s.id))},
  "starterWallet": ${line({ [CURRENCY]: STARTER_CANDLES })}
}
`;

const target = join(CONTENT, 'store.json');
if (flag('--check')) {
  const cur = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (cur !== text) { console.error('content/store.json is out of date: run node tools/gen_store.ts'); process.exit(1); }
  console.log(`store.json is current (${offers.length} offers, ${shelves.length} shelves)`);
} else {
  writeFileSync(target, text);
  const fightersWithSkins = new Set(skins.map((s) => s.fighter));
  console.log(`wrote ${target}: ${offers.length} offers, ${shelves.length} shelves, ${base.length} starter skins, ${fightersWithSkins.size} fighters with skins (${skinFiles.length} skin files)`);
}
