// HIT PARADE - audio manifest. GENERATED by runtime/src/audio/build/build_audio.py: do not edit by hand, fix the generator
// and rebuild. THREE-free, DOM-free (the URLs are plain `new URL(..., import.meta.url)`: Vite emits the hashed files,
// Node resolves them to file: URLs for _harness/probe_audio.ts).

export type SfxId =
  | 'ui_move'
  | 'ui_confirm'
  | 'ui_back'
  | 'ui_error'
  | 'ui_toggle'
  | 'ui_start'
  | 'ui_lock'
  | 'ui_vs'
  | 'ui_pause'
  | 'ui_resume'
  | 'ui_tick'
  | 'ui_cash'
  | 'ui_unlock'
  | 'ui_ladder'
  | 'hit_l'
  | 'hit_m'
  | 'hit_h'
  | 'hit_sp'
  | 'hit_ctr'
  | 'hit_pun'
  | 'whiff_l'
  | 'whiff_m'
  | 'whiff_h'
  | 'block_l'
  | 'block_h'
  | 'throw_grab'
  | 'throw_slam'
  | 'throw_tech'
  | 'parry'
  | 'parry_perfect'
  | 'impact_start'
  | 'impact_armor'
  | 'impact_clash'
  | 'shove'
  | 'wall_splat'
  | 'ground_bounce'
  | 'knockdown'
  | 'wakeup'
  | 'crumple'
  | 'dizzy'
  | 'proj_throw'
  | 'proj_card'
  | 'proj_ball'
  | 'proj_zap'
  | 'proj_fire'
  | 'proj_hit'
  | 'proj_clash'
  | 'super_freeze'
  | 'super_hit'
  | 'ko_hit'
  | 'stage_fright'
  | 'meter_bar'
  | 'meter_full'
  | 'splat'
  | 'sparks'
  | 'confetti'
  | 'taunt'
  | 'slap'
  | 'clang'
  | 'wood_crack'
  | 'glass_break'
  | 'explosion'
  | 'goon_down'
  | 'heckle_throw'
  | 'heckle_smash'
  | 'score'
  | 'bell_round'
  | 'bell_ko'
  | 'bell_end'
  | 'horn'
  | 'buzzer'
  | 'roar'
  | 'host_laugh'
  | 'host_pos'
  | 'host_neg'
  | 'host_fanfare'
  | 'ann_ready'
  | 'ann_fight'
  | 'ann_timeup'
  | 'ann_victory'
  | 'ann_win'
  | 'ann_lose'
  | 'ann_gameover'
  | 'ann_wow'
  | 'ann_ohyeah'
  | 'ann_bonus'
  | 'ann_begin'
  | 'ann_go'
  | 'ann_1'
  | 'ann_2'
  | 'ann_3'
  | 'ann_combo_quad'
  | 'ann_combo_super'
  | 'ann_combo_mega'
  | 'ann_combo_ultra'
  | 'ann_combo_monster'
  | 'vo_m1_atk'
  | 'vo_m1_hurt'
  | 'vo_m1_ko'
  | 'vo_m2_atk'
  | 'vo_m2_hurt'
  | 'vo_m2_ko'
  | 'vo_m3_atk'
  | 'vo_m3_hurt'
  | 'vo_m3_ko'
  | 'vo_f1_atk'
  | 'vo_f1_hurt'
  | 'vo_f1_ko'
  | 'vo_f2_atk'
  | 'vo_f2_hurt'
  | 'vo_f2_ko'
  | 'vo_mon_atk'
  | 'vo_mon_hurt'
  | 'vo_mon_ko'
  | 'bed_low'
  | 'bed_high'
  | 'bed_stomp'
  | 'crowd_cheer'
  | 'crowd_roar'
  | 'crowd_ooh'
  | 'crowd_ouch'
  | 'crowd_boo'
  | 'crowd_applause'
  | 'crowd_laugh'
  | 'crowd_claps';
export type SfxCategory = 'ann' | 'bed' | 'bell' | 'block' | 'body' | 'crowd' | 'foley' | 'hit' | 'impact' | 'layer' | 'splat' | 'sting' | 'super' | 'ui' | 'voice' | 'whiff';
export type SpriteId = 'ui' | 'sfx' | 'crowd';
export type MusicCueId = 'menu' | 'select' | 'rust_theater' | 'butcher_block' | 'wheel_of_pain' | 'rooftop' | 'control_room' | 'boss' | 'miniboss' | 'win' | 'lose';

/** the AAC-LC (MP4) twin of an Ogg asset, for WebKit before 18.4 (no Ogg decode): `samples` = the decode that honours
 *  the MP4 edit list; a decoder that ignores it returns `samples` + `delay` priming samples first (engine.ts skips them) */
export interface AltCodec { readonly url: string; readonly file: string; readonly bytes: number; readonly samples: number; readonly delay: number }
export interface SpriteEntry {
  readonly url: string; readonly file: string; readonly channels: number; readonly seconds: number;
  readonly samples: number; readonly bytes: number; readonly alt: AltCodec;
}
export interface SfxEntry {
  readonly sprite: SpriteId;
  /** variants: [start s, duration s] inside the sprite */
  readonly v: readonly (readonly [number, number])[];
  /** variant lengths in samples at SAMPLE_RATE (exact) */
  readonly n: readonly number[];
  readonly loop: boolean;
  readonly cat: SfxCategory;
  /** perceived level of the mastered take (dBFS RMS of its loudest 400 ms); the router levels by category */
  readonly ldb: number;
}
export interface MusicEntry {
  readonly url: string; readonly file: string; readonly alt: AltCodec;
  readonly seconds: number; readonly samples: number; readonly bytes: number;
  /** looping cues: whole bars at `bpm`; stingers play once */
  readonly loop: boolean; readonly bpm: number; readonly bars: number;
  readonly lufs: number; readonly track: string;
}

export const SAMPLE_RATE = 48000;
/** s of wrap-around written before and after every loop region (seam.ts crossfades the head from it) */
export const SPRITE_GUARD_S = 0.06;

export const SPRITES: { readonly [K in SpriteId]: SpriteEntry } = {
  ui: { url: new URL('./assets/ui.ogg', import.meta.url).href, file: 'assets/ui.ogg', channels: 1, seconds: 9.594625, samples: 460542, bytes: 59393, alt: { url: new URL('./assets/ui.m4a', import.meta.url).href, file: 'assets/ui.m4a', bytes: 85644, samples: 460800, delay: 1024 } },
  sfx: { url: new URL('./assets/sfx.ogg', import.meta.url).href, file: 'assets/sfx.ogg', channels: 1, seconds: 148.719146, samples: 7138519, bytes: 810917, alt: { url: new URL('./assets/sfx.m4a', import.meta.url).href, file: 'assets/sfx.m4a', bytes: 1205372, samples: 7139328, delay: 1024 } },
  crowd: { url: new URL('./assets/crowd.ogg', import.meta.url).href, file: 'assets/crowd.ogg', channels: 2, seconds: 56.207146, samples: 2697943, bytes: 438652, alt: { url: new URL('./assets/crowd.m4a', import.meta.url).href, file: 'assets/crowd.m4a', bytes: 589514, samples: 2698240, delay: 1024 } },
};

export const SFX: { readonly [K in SfxId]: SfxEntry } = {
  ui_move: { sprite: 'ui', v: [[0.05, 0.054583], [0.154583, 0.032458]], n: [2620, 1558], loop: false, cat: 'ui', ldb: -18.5 },
  ui_confirm: { sprite: 'ui', v: [[0.237042, 0.232667]], n: [11168], loop: false, cat: 'ui', ldb: -25.8 },
  ui_back: { sprite: 'ui', v: [[0.519708, 0.354667]], n: [17024], loop: false, cat: 'ui', ldb: -23.9 },
  ui_error: { sprite: 'ui', v: [[0.924375, 0.492542]], n: [23642], loop: false, cat: 'ui', ldb: -18.1 },
  ui_toggle: { sprite: 'ui', v: [[1.466917, 0.202625], [1.719542, 0.199646]], n: [9726, 9583], loop: false, cat: 'ui', ldb: -17.0 },
  ui_start: { sprite: 'ui', v: [[1.969188, 0.965479]], n: [46343], loop: false, cat: 'sting', ldb: -15.7 },
  ui_lock: { sprite: 'ui', v: [[2.984667, 0.950792]], n: [45638], loop: false, cat: 'ui', ldb: -18.4 },
  ui_vs: { sprite: 'ui', v: [[3.985458, 1.423646]], n: [68335], loop: false, cat: 'sting', ldb: -16.6 },
  ui_pause: { sprite: 'ui', v: [[5.459104, 0.250063]], n: [12003], loop: false, cat: 'ui', ldb: -12.6 },
  ui_resume: { sprite: 'ui', v: [[5.759167, 0.247583]], n: [11884], loop: false, cat: 'ui', ldb: -15.1 },
  ui_tick: { sprite: 'ui', v: [[6.05675, 0.325375]], n: [15618], loop: false, cat: 'ui', ldb: -19.4 },
  ui_cash: { sprite: 'ui', v: [[6.432125, 0.617875]], n: [29658], loop: false, cat: 'sting', ldb: -18.4 },
  ui_unlock: { sprite: 'ui', v: [[7.1, 2.137833]], n: [102616], loop: false, cat: 'sting', ldb: -11.3 },
  ui_ladder: { sprite: 'ui', v: [[9.287833, 0.256792]], n: [12326], loop: false, cat: 'ui', ldb: -25.1 },
  hit_l: { sprite: 'sfx', v: [[0.05, 0.302625], [0.402625, 0.33725], [0.789875, 0.344292], [1.184167, 0.302646], [1.536812, 0.299833], [1.886646, 0.264125]], n: [14526, 16188, 16526, 14527, 14392, 12678], loop: false, cat: 'hit', ldb: -24.4 },
  hit_m: { sprite: 'sfx', v: [[2.200771, 0.37125], [2.622021, 0.409562], [3.081583, 0.442333], [3.573917, 0.365354], [3.989271, 0.369542], [4.408812, 0.341604]], n: [17820, 19659, 21232, 17537, 17738, 16397], loop: false, cat: 'hit', ldb: -21.4 },
  hit_h: { sprite: 'sfx', v: [[4.800417, 0.732375], [5.582792, 0.438979], [6.071771, 0.583708], [6.705479, 0.609938], [7.365417, 0.730208], [8.145625, 0.583396]], n: [35154, 21071, 28018, 29277, 35050, 28003], loop: false, cat: 'hit', ldb: -22.0 },
  hit_sp: { sprite: 'sfx', v: [[8.779021, 0.609333], [9.438354, 0.649396], [10.13775, 0.609333]], n: [29248, 31171, 29248], loop: false, cat: 'super', ldb: -19.3 },
  hit_ctr: { sprite: 'sfx', v: [[10.797083, 0.348938], [11.196021, 0.300292], [11.546313, 0.386042]], n: [16749, 14414, 18530], loop: false, cat: 'layer', ldb: -21.0 },
  hit_pun: { sprite: 'sfx', v: [[11.982354, 0.650958], [12.683312, 0.535833]], n: [31246, 25720], loop: false, cat: 'layer', ldb: -18.4 },
  whiff_l: { sprite: 'sfx', v: [[13.269146, 0.224042], [13.543188, 0.235021], [13.828208, 0.235833], [14.114042, 0.232521]], n: [10754, 11281, 11320, 11161], loop: false, cat: 'whiff', ldb: -17.3 },
  whiff_m: { sprite: 'sfx', v: [[14.396562, 0.182271], [14.628833, 0.182958], [14.861792, 0.184792]], n: [8749, 8782, 8870], loop: false, cat: 'whiff', ldb: -17.0 },
  whiff_h: { sprite: 'sfx', v: [[15.096583, 0.259729], [15.406313, 0.289271], [15.745583, 0.287917]], n: [12467, 13885, 13820], loop: false, cat: 'whiff', ldb: -18.9 },
  block_l: { sprite: 'sfx', v: [[16.0835, 0.346167], [16.479667, 0.325646], [16.855313, 0.2635]], n: [16616, 15631, 12648], loop: false, cat: 'block', ldb: -23.8 },
  block_h: { sprite: 'sfx', v: [[17.168813, 0.391146], [17.609958, 0.365438], [18.025396, 0.365646]], n: [18775, 17541, 17551], loop: false, cat: 'block', ldb: -19.6 },
  throw_grab: { sprite: 'sfx', v: [[18.441042, 0.400313], [18.891354, 0.437812]], n: [19215, 21015], loop: false, cat: 'body', ldb: -22.6 },
  throw_slam: { sprite: 'sfx', v: [[19.379167, 0.610958], [20.040125, 0.609875]], n: [29326, 29274], loop: false, cat: 'body', ldb: -20.9 },
  throw_tech: { sprite: 'sfx', v: [[20.7, 0.592542]], n: [28442], loop: false, cat: 'impact', ldb: -19.8 },
  parry: { sprite: 'sfx', v: [[21.342542, 0.619979], [22.012521, 0.758771]], n: [29759, 36421], loop: false, cat: 'impact', ldb: -19.4 },
  parry_perfect: { sprite: 'sfx', v: [[22.821292, 0.981833]], n: [47128], loop: false, cat: 'sting', ldb: -16.4 },
  impact_start: { sprite: 'sfx', v: [[23.853125, 0.830708]], n: [39874], loop: false, cat: 'impact', ldb: -16.3 },
  impact_armor: { sprite: 'sfx', v: [[24.733833, 0.371771], [25.155604, 1.048396]], n: [17845, 50323], loop: false, cat: 'impact', ldb: -21.9 },
  impact_clash: { sprite: 'sfx', v: [[26.254, 1.919083]], n: [92116], loop: false, cat: 'super', ldb: -19.8 },
  shove: { sprite: 'sfx', v: [[28.223083, 0.566333]], n: [27184], loop: false, cat: 'body', ldb: -20.0 },
  wall_splat: { sprite: 'sfx', v: [[28.839417, 0.721021], [29.610437, 0.604708], [30.265146, 0.496729]], n: [34609, 29026, 23843], loop: false, cat: 'body', ldb: -24.2 },
  ground_bounce: { sprite: 'sfx', v: [[30.811875, 0.57575], [31.437625, 0.57575]], n: [27636, 27636], loop: false, cat: 'body', ldb: -20.8 },
  knockdown: { sprite: 'sfx', v: [[32.063375, 0.787875], [32.90125, 0.724042], [33.675292, 0.613812]], n: [37818, 34754, 29463], loop: false, cat: 'body', ldb: -20.3 },
  wakeup: { sprite: 'sfx', v: [[34.339104, 0.78725], [35.176354, 0.923292]], n: [37788, 44318], loop: false, cat: 'foley', ldb: -18.0 },
  crumple: { sprite: 'sfx', v: [[36.149646, 1.849354]], n: [88769], loop: false, cat: 'body', ldb: -23.2 },
  dizzy: { sprite: 'sfx', v: [[38.049, 1.590271]], n: [76333], loop: false, cat: 'sting', ldb: -15.8 },
  proj_throw: { sprite: 'sfx', v: [[39.689271, 0.098875], [39.838146, 0.123375]], n: [4746, 5922], loop: false, cat: 'whiff', ldb: -19.8 },
  proj_card: { sprite: 'sfx', v: [[40.011521, 0.406813], [40.468333, 0.405604]], n: [19527, 19469], loop: false, cat: 'whiff', ldb: -24.3 },
  proj_ball: { sprite: 'sfx', v: [[40.923938, 0.248604], [41.222542, 0.299104]], n: [11933, 14357], loop: false, cat: 'impact', ldb: -23.9 },
  proj_zap: { sprite: 'sfx', v: [[41.571646, 0.705708]], n: [33874], loop: false, cat: 'impact', ldb: -19.9 },
  proj_fire: { sprite: 'sfx', v: [[42.327354, 0.80625]], n: [38700], loop: false, cat: 'impact', ldb: -15.2 },
  proj_hit: { sprite: 'sfx', v: [[43.183604, 0.350958], [43.584562, 0.397437]], n: [16846, 19077], loop: false, cat: 'impact', ldb: -18.2 },
  proj_clash: { sprite: 'sfx', v: [[44.032, 0.619563]], n: [29739], loop: false, cat: 'impact', ldb: -19.3 },
  super_freeze: { sprite: 'sfx', v: [[44.701563, 0.973042]], n: [46706], loop: false, cat: 'sting', ldb: -15.1 },
  super_hit: { sprite: 'sfx', v: [[45.724604, 0.609333], [46.383938, 0.973812], [47.40775, 0.807125]], n: [29248, 46743, 38742], loop: false, cat: 'super', ldb: -18.8 },
  ko_hit: { sprite: 'sfx', v: [[48.264875, 0.973229]], n: [46715], loop: false, cat: 'super', ldb: -20.1 },
  stage_fright: { sprite: 'sfx', v: [[49.288104, 1.892813]], n: [90855], loop: false, cat: 'sting', ldb: -14.6 },
  meter_bar: { sprite: 'sfx', v: [[51.230917, 0.427917]], n: [20540], loop: false, cat: 'ui', ldb: -18.3 },
  meter_full: { sprite: 'sfx', v: [[51.708833, 1.203188]], n: [57753], loop: false, cat: 'sting', ldb: -13.7 },
  splat: { sprite: 'sfx', v: [[52.962021, 0.249833], [53.261854, 0.535271], [53.847125, 0.574438], [54.471562, 0.497563]], n: [11992, 25693, 27573, 23883], loop: false, cat: 'splat', ldb: -20.6 },
  sparks: { sprite: 'sfx', v: [[55.019125, 0.22875], [55.297875, 0.121958]], n: [10980, 5854], loop: false, cat: 'splat', ldb: -16.8 },
  confetti: { sprite: 'sfx', v: [[55.469833, 1.421646], [56.941479, 1.408604]], n: [68239, 67613], loop: false, cat: 'splat', ldb: -19.2 },
  taunt: { sprite: 'sfx', v: [[58.400083, 0.346917], [58.797, 1.777813]], n: [16652, 85335], loop: false, cat: 'sting', ldb: -10.6 },
  slap: { sprite: 'sfx', v: [[60.624812, 0.306604], [60.981417, 0.310667], [61.342083, 0.276562]], n: [14717, 14912, 13275], loop: false, cat: 'impact', ldb: -19.7 },
  clang: { sprite: 'sfx', v: [[61.668646, 0.305812], [62.024458, 1.166729]], n: [14679, 56003], loop: false, cat: 'impact', ldb: -17.5 },
  wood_crack: { sprite: 'sfx', v: [[63.241188, 0.555], [63.846187, 0.378104]], n: [26640, 18149], loop: false, cat: 'impact', ldb: -23.6 },
  glass_break: { sprite: 'sfx', v: [[64.274292, 0.719396]], n: [34531], loop: false, cat: 'impact', ldb: -20.7 },
  explosion: { sprite: 'sfx', v: [[65.043688, 0.641875], [65.735563, 0.379979]], n: [30810, 18239], loop: false, cat: 'super', ldb: -17.5 },
  goon_down: { sprite: 'sfx', v: [[66.165542, 0.783479], [66.999021, 0.430292]], n: [37607, 20654], loop: false, cat: 'body', ldb: -21.6 },
  heckle_throw: { sprite: 'sfx', v: [[67.479313, 0.082771], [67.612083, 0.180521]], n: [3973, 8665], loop: false, cat: 'whiff', ldb: -15.5 },
  heckle_smash: { sprite: 'sfx', v: [[67.842604, 1.367792], [69.260396, 0.860688]], n: [65654, 41313], loop: false, cat: 'impact', ldb: -19.7 },
  score: { sprite: 'sfx', v: [[70.171083, 1.306146]], n: [62695], loop: false, cat: 'ui', ldb: -20.8 },
  bell_round: { sprite: 'sfx', v: [[71.527229, 0.719146]], n: [34519], loop: false, cat: 'bell', ldb: -15.3 },
  bell_ko: { sprite: 'sfx', v: [[72.296375, 0.992208]], n: [47626], loop: false, cat: 'bell', ldb: -12.3 },
  bell_end: { sprite: 'sfx', v: [[73.338583, 2.375667]], n: [114032], loop: false, cat: 'bell', ldb: -13.9 },
  horn: { sprite: 'sfx', v: [[75.76425, 0.944688]], n: [45345], loop: false, cat: 'bell', ldb: -10.2 },
  buzzer: { sprite: 'sfx', v: [[76.758938, 0.949854]], n: [45593], loop: false, cat: 'bell', ldb: -14.7 },
  roar: { sprite: 'sfx', v: [[77.758792, 1.389063]], n: [66675], loop: false, cat: 'voice', ldb: -16.9 },
  host_laugh: { sprite: 'sfx', v: [[79.197854, 1.631771], [80.879625, 2.197687], [83.127313, 1.431229]], n: [78325, 105489, 68699], loop: false, cat: 'voice', ldb: -16.4 },
  host_pos: { sprite: 'sfx', v: [[84.608542, 2.021542], [86.680083, 1.683188], [88.413271, 1.667583]], n: [97034, 80793, 80044], loop: false, cat: 'sting', ldb: -12.6 },
  host_neg: { sprite: 'sfx', v: [[90.130854, 1.707208], [91.888063, 1.683917]], n: [81946, 80828], loop: false, cat: 'sting', ldb: -14.4 },
  host_fanfare: { sprite: 'sfx', v: [[93.621979, 1.150208]], n: [55210], loop: false, cat: 'sting', ldb: -14.3 },
  ann_ready: { sprite: 'sfx', v: [[94.822187, 0.605646]], n: [29071], loop: false, cat: 'ann', ldb: -16.0 },
  ann_fight: { sprite: 'sfx', v: [[95.477833, 0.597083]], n: [28660], loop: false, cat: 'ann', ldb: -13.7 },
  ann_timeup: { sprite: 'sfx', v: [[96.124917, 0.739021]], n: [35473], loop: false, cat: 'ann', ldb: -13.6 },
  ann_victory: { sprite: 'sfx', v: [[96.913938, 1.002583]], n: [48124], loop: false, cat: 'ann', ldb: -11.9 },
  ann_win: { sprite: 'sfx', v: [[97.966521, 1.173583]], n: [56332], loop: false, cat: 'ann', ldb: -11.7 },
  ann_lose: { sprite: 'sfx', v: [[99.190104, 0.904958]], n: [43438], loop: false, cat: 'ann', ldb: -10.5 },
  ann_gameover: { sprite: 'sfx', v: [[100.145062, 1.257875]], n: [60378], loop: false, cat: 'ann', ldb: -9.7 },
  ann_wow: { sprite: 'sfx', v: [[101.452938, 0.629021]], n: [30193], loop: false, cat: 'ann', ldb: -12.5 },
  ann_ohyeah: { sprite: 'sfx', v: [[102.131958, 1.051417]], n: [50468], loop: false, cat: 'ann', ldb: -9.6 },
  ann_bonus: { sprite: 'sfx', v: [[103.233375, 0.771417]], n: [37028], loop: false, cat: 'ann', ldb: -13.6 },
  ann_begin: { sprite: 'sfx', v: [[104.054792, 0.654896]], n: [31435], loop: false, cat: 'ann', ldb: -16.0 },
  ann_go: { sprite: 'sfx', v: [[104.759687, 0.793375]], n: [38082], loop: false, cat: 'ann', ldb: -11.4 },
  ann_1: { sprite: 'sfx', v: [[105.603062, 0.553646]], n: [26575], loop: false, cat: 'ann', ldb: -14.1 },
  ann_2: { sprite: 'sfx', v: [[106.206708, 0.539521]], n: [25897], loop: false, cat: 'ann', ldb: -11.9 },
  ann_3: { sprite: 'sfx', v: [[106.796229, 0.574313]], n: [27567], loop: false, cat: 'ann', ldb: -13.9 },
  ann_combo_quad: { sprite: 'sfx', v: [[107.420542, 1.081187]], n: [51897], loop: false, cat: 'ann', ldb: -11.4 },
  ann_combo_super: { sprite: 'sfx', v: [[108.551729, 1.379646]], n: [66223], loop: false, cat: 'ann', ldb: -10.8 },
  ann_combo_mega: { sprite: 'sfx', v: [[109.981375, 1.494542]], n: [71738], loop: false, cat: 'ann', ldb: -8.7 },
  ann_combo_ultra: { sprite: 'sfx', v: [[111.525917, 1.366437]], n: [65589], loop: false, cat: 'ann', ldb: -11.5 },
  ann_combo_monster: { sprite: 'sfx', v: [[112.942354, 2.087667]], n: [100208], loop: false, cat: 'ann', ldb: -8.9 },
  vo_m1_atk: { sprite: 'sfx', v: [[115.080021, 0.262688], [115.392708, 0.305021], [115.747729, 0.311875], [116.109604, 0.448417]], n: [12609, 14641, 14970, 21524], loop: false, cat: 'voice', ldb: -14.9 },
  vo_m1_hurt: { sprite: 'sfx', v: [[116.608021, 0.381521], [117.039542, 0.466667], [117.556208, 0.399396], [118.005604, 0.32275]], n: [18313, 22400, 19171, 15492], loop: false, cat: 'voice', ldb: -15.7 },
  vo_m1_ko: { sprite: 'sfx', v: [[118.378354, 1.044]], n: [50112], loop: false, cat: 'voice', ldb: -13.6 },
  vo_m2_atk: { sprite: 'sfx', v: [[119.472354, 0.269937], [119.792292, 0.250812], [120.093104, 0.277333], [120.420438, 0.269375]], n: [12957, 12039, 13312, 12930], loop: false, cat: 'voice', ldb: -15.0 },
  vo_m2_hurt: { sprite: 'sfx', v: [[120.739812, 0.347938], [121.13775, 0.519521], [121.707271, 0.214625], [121.971896, 0.516604]], n: [16701, 24937, 10302, 24797], loop: false, cat: 'voice', ldb: -15.9 },
  vo_m2_ko: { sprite: 'sfx', v: [[122.5385, 1.421083]], n: [68212], loop: false, cat: 'voice', ldb: -11.3 },
  vo_m3_atk: { sprite: 'sfx', v: [[124.009583, 0.172167], [124.23175, 0.467292], [124.749042, 0.299729], [125.098771, 0.327146]], n: [8264, 22430, 14387, 15703], loop: false, cat: 'voice', ldb: -14.6 },
  vo_m3_hurt: { sprite: 'sfx', v: [[125.475917, 0.502042], [126.027958, 0.464], [126.541958, 0.568333], [127.160292, 0.789188]], n: [24098, 22272, 27280, 37881], loop: false, cat: 'voice', ldb: -13.1 },
  vo_m3_ko: { sprite: 'sfx', v: [[127.999479, 1.068354]], n: [51281], loop: false, cat: 'voice', ldb: -14.0 },
  vo_f1_atk: { sprite: 'sfx', v: [[129.117833, 0.689708], [129.857542, 0.662854], [130.570396, 0.692583], [131.312979, 0.478333]], n: [33106, 31817, 33244, 22960], loop: false, cat: 'voice', ldb: -13.8 },
  vo_f1_hurt: { sprite: 'sfx', v: [[131.841312, 0.741771], [132.633083, 0.698688], [133.381771, 0.671167], [134.102937, 0.375646]], n: [35605, 33537, 32216, 18031], loop: false, cat: 'voice', ldb: -15.5 },
  vo_f1_ko: { sprite: 'sfx', v: [[134.528583, 1.291813]], n: [62007], loop: false, cat: 'voice', ldb: -11.3 },
  vo_f2_atk: { sprite: 'sfx', v: [[135.870396, 0.489375], [136.409771, 0.582271], [137.042042, 0.272396], [137.364438, 0.398417]], n: [23490, 27949, 13075, 19124], loop: false, cat: 'voice', ldb: -14.3 },
  vo_f2_hurt: { sprite: 'sfx', v: [[137.812854, 0.233104], [138.095958, 0.275813], [138.421771, 0.186375], [138.658146, 0.257833]], n: [11189, 13239, 8946, 12376], loop: false, cat: 'voice', ldb: -13.4 },
  vo_f2_ko: { sprite: 'sfx', v: [[138.965979, 1.583479]], n: [76007], loop: false, cat: 'voice', ldb: -12.2 },
  vo_mon_atk: { sprite: 'sfx', v: [[140.599458, 0.771188], [141.420646, 0.713187], [142.183833, 0.796562], [143.030396, 0.773833]], n: [37017, 34233, 38235, 37144], loop: false, cat: 'voice', ldb: -16.2 },
  vo_mon_hurt: { sprite: 'sfx', v: [[143.854229, 0.586333], [144.490563, 0.786375], [145.326938, 0.793729], [146.170667, 0.792271]], n: [28144, 37746, 38099, 38029], loop: false, cat: 'voice', ldb: -13.4 },
  vo_mon_ko: { sprite: 'sfx', v: [[147.012937, 1.656208]], n: [79498], loop: false, cat: 'voice', ldb: -9.8 },
  bed_low: { sprite: 'crowd', v: [[0.11, 10.49875]], n: [503940], loop: true, cat: 'bed', ldb: -19.3 },
  bed_high: { sprite: 'crowd', v: [[10.77875, 7.818146]], n: [375271], loop: true, cat: 'bed', ldb: -24.2 },
  bed_stomp: { sprite: 'crowd', v: [[18.766896, 1.245854]], n: [59801], loop: true, cat: 'bed', ldb: -21.4 },
  crowd_cheer: { sprite: 'crowd', v: [[20.12275, 2.993417], [23.166167, 2.964417], [26.180583, 2.840458]], n: [143684, 142292, 136342], loop: false, cat: 'crowd', ldb: -15.8 },
  crowd_roar: { sprite: 'crowd', v: [[29.071042, 3.375812], [32.496854, 3.068208]], n: [162039, 147274], loop: false, cat: 'crowd', ldb: -18.4 },
  crowd_ooh: { sprite: 'crowd', v: [[35.615063, 2.265708]], n: [108754], loop: false, cat: 'crowd', ldb: -17.8 },
  crowd_ouch: { sprite: 'crowd', v: [[37.930771, 2.157958]], n: [103582], loop: false, cat: 'crowd', ldb: -26.1 },
  crowd_boo: { sprite: 'crowd', v: [[40.138729, 1.521062], [41.709792, 2.233208], [43.993, 2.563896]], n: [73011, 107194, 123067], loop: false, cat: 'crowd', ldb: -16.7 },
  crowd_applause: { sprite: 'crowd', v: [[46.606896, 2.677], [49.333896, 2.981313]], n: [128496, 143103], loop: false, cat: 'crowd', ldb: -18.6 },
  crowd_laugh: { sprite: 'crowd', v: [[52.365208, 1.568125], [53.983333, 1.694438]], n: [75270, 81333], loop: false, cat: 'crowd', ldb: -18.3 },
  crowd_claps: { sprite: 'crowd', v: [[55.727771, 0.429375]], n: [20610], loop: false, cat: 'crowd', ldb: -23.1 },
};

export const MUSIC: { readonly [K in MusicCueId]: MusicEntry } = {
  menu: {
    url: new URL('./assets/music_menu.ogg', import.meta.url).href, file: 'assets/music_menu.ogg',
    alt: { url: new URL('./assets/music_menu.m4a', import.meta.url).href, file: 'assets/music_menu.m4a', bytes: 327956, samples: 1536000, delay: 1024 },
    seconds: 32.0, samples: 1536000, bytes: 266917,
    loop: true, bpm: 90, bars: 12, lufs: -17.0, track: 'Beginning',
  },
  select: {
    url: new URL('./assets/music_select.ogg', import.meta.url).href, file: 'assets/music_select.ogg',
    alt: { url: new URL('./assets/music_select.m4a', import.meta.url).href, file: 'assets/music_select.m4a', bytes: 329425, samples: 1536000, delay: 1024 },
    seconds: 32.0, samples: 1536000, bytes: 263476,
    loop: true, bpm: 90, bars: 12, lufs: -17.0, track: 'Arrival',
  },
  rust_theater: {
    url: new URL('./assets/music_rust_theater.ogg', import.meta.url).href, file: 'assets/music_rust_theater.ogg',
    alt: { url: new URL('./assets/music_rust_theater.m4a', import.meta.url).href, file: 'assets/music_rust_theater.m4a', bytes: 396265, samples: 1843200, delay: 1024 },
    seconds: 38.4, samples: 1843200, bytes: 327507,
    loop: true, bpm: 100, bars: 16, lufs: -16.0, track: 'Outbreak',
  },
  butcher_block: {
    url: new URL('./assets/music_butcher_block.ogg', import.meta.url).href, file: 'assets/music_butcher_block.ogg',
    alt: { url: new URL('./assets/music_butcher_block.m4a', import.meta.url).href, file: 'assets/music_butcher_block.m4a', bytes: 396379, samples: 1843200, delay: 1024 },
    seconds: 38.4, samples: 1843200, bytes: 325579,
    loop: true, bpm: 100, bars: 16, lufs: -16.0, track: 'Disorder',
  },
  wheel_of_pain: {
    url: new URL('./assets/music_wheel_of_pain.ogg', import.meta.url).href, file: 'assets/music_wheel_of_pain.ogg',
    alt: { url: new URL('./assets/music_wheel_of_pain.m4a', import.meta.url).href, file: 'assets/music_wheel_of_pain.m4a', bytes: 394584, samples: 1843200, delay: 1024 },
    seconds: 38.4, samples: 1843200, bytes: 311957,
    loop: true, bpm: 100, bars: 16, lufs: -16.0, track: 'RETROWAVE',
  },
  rooftop: {
    url: new URL('./assets/music_rooftop.ogg', import.meta.url).href, file: 'assets/music_rooftop.ogg',
    alt: { url: new URL('./assets/music_rooftop.m4a', import.meta.url).href, file: 'assets/music_rooftop.m4a', bytes: 358017, samples: 1676288, delay: 1024 },
    seconds: 34.909083, samples: 1675636, bytes: 284004,
    loop: true, bpm: 110, bars: 16, lufs: -16.0, track: 'Electric Phase',
  },
  control_room: {
    url: new URL('./assets/music_control_room.ogg', import.meta.url).href, file: 'assets/music_control_room.ogg',
    alt: { url: new URL('./assets/music_control_room.m4a', import.meta.url).href, file: 'assets/music_control_room.m4a', bytes: 393660, samples: 1843200, delay: 1024 },
    seconds: 38.4, samples: 1843200, bytes: 295953,
    loop: true, bpm: 100, bars: 16, lufs: -16.0, track: 'Chasm',
  },
  boss: {
    url: new URL('./assets/music_boss.ogg', import.meta.url).href, file: 'assets/music_boss.ogg',
    alt: { url: new URL('./assets/music_boss.m4a', import.meta.url).href, file: 'assets/music_boss.m4a', bytes: 394238, samples: 1843200, delay: 1024 },
    seconds: 38.4, samples: 1843200, bytes: 328680,
    loop: true, bpm: 100, bars: 16, lufs: -15.5, track: 'Anxiety',
  },
  miniboss: {
    url: new URL('./assets/music_miniboss.ogg', import.meta.url).href, file: 'assets/music_miniboss.ogg',
    alt: { url: new URL('./assets/music_miniboss.m4a', import.meta.url).href, file: 'assets/music_miniboss.m4a', bytes: 329663, samples: 1536000, delay: 1024 },
    seconds: 32.0, samples: 1536000, bytes: 294114,
    loop: true, bpm: 90, bars: 12, lufs: -16.0, track: 'Darkness Behind',
  },
  win: {
    url: new URL('./assets/music_win.ogg', import.meta.url).href, file: 'assets/music_win.ogg',
    alt: { url: new URL('./assets/music_win.m4a', import.meta.url).href, file: 'assets/music_win.m4a', bytes: 83955, samples: 396288, delay: 1024 },
    seconds: 8.25, samples: 396000, bytes: 54483,
    loop: false, bpm: 100, bars: 0, lufs: -15.0, track: 'Outbreak',
  },
  lose: {
    url: new URL('./assets/music_lose.ogg', import.meta.url).href, file: 'assets/music_lose.ogg',
    alt: { url: new URL('./assets/music_lose.m4a', import.meta.url).href, file: 'assets/music_lose.m4a', bytes: 103123, samples: 508928, delay: 1024 },
    seconds: 10.6, samples: 508800, bytes: 94240,
    loop: false, bpm: 90, bars: 0, lufs: -16.5, track: 'Darkness Behind',
  },
};

/** every shipped Ogg byte (sprites + music) */
export const AUDIO_PAYLOAD_BYTES = 4155872;
/** the AAC twins' bytes (a device downloads one set: Ogg, or these on WebKit before 18.4) */
export const AUDIO_ALT_PAYLOAD_BYTES = 5387795;
/** CONTRACT s9 budget: Ogg + AAC together (everything dist/ carries) */
export const AUDIO_BUDGET_BYTES = 12000000;
/** tracks registered for the slug `hit-parade` in state/music_assignments.json */
export const REGISTERED_TRACKS = ['Travis Rise/SynthWave Music Pack 2/01_Beginning', 'Travis Rise/SynthWave Music Pack 2/02_Outbreak', 'Travis Rise/SynthWave Music Pack 2/03_Disorder', 'Travis Rise/SynthWave Music Pack 2/04_Anxiety', 'Travis Rise/SynthWave Music Pack 2/05_Chasm', 'Travis Rise/SynthWave Music Pack 2/06_Arrival', 'Travis Rise/SynthWave Music Pack/03_DarknessBehind', 'Travis Rise/SynthWave Music Pack/04_ElectricPhase', 'Travis Rise/SynthWave Music Pack/07_RETROWAVE'] as const;
