// DYEFIELD — audio manifest. GENERATED by runtime/src/audio/build/build_audio.py: do not edit by hand, fix the generator
// and rebuild. THREE-free, DOM-free (the URLs are plain `new URL(..., import.meta.url)`: Vite emits the hashed files,
// Node resolves them to file: URLs for _harness/probe_audio.ts).

export type SfxId =
  | 'ui_hover'
  | 'ui_click'
  | 'ui_back'
  | 'ui_start'
  | 'beep'
  | 'beep_go'
  | 'tick'
  | 'horn_start'
  | 'horn_minute'
  | 'horn_final'
  | 'horn_end'
  | 'special_ready'
  | 'tank_low'
  | 'confirm'
  | 'shot_mist'
  | 'shot_drum'
  | 'roll_loop'
  | 'flick'
  | 'shot_needle'
  | 'shot_pop'
  | 'burst'
  | 'splat'
  | 'dry'
  | 'hit_dealt'
  | 'hit_taken'
  | 'washed_me'
  | 'washed'
  | 'respawn'
  | 'slick_in'
  | 'slick_out'
  | 'swim_loop'
  | 'refill_loop'
  | 'jump'
  | 'land'
  | 'land_hard'
  | 'sub_throw'
  | 'sub_land'
  | 'sub_pop'
  | 'cloud_throw'
  | 'thunder'
  | 'rain_loop'
  | 'leap'
  | 'slam'
  | 'spring'
  | 'conveyor_loop'
  | 'amb_harbor'
  | 'amb_works';
export type SfxCategory = 'amb' | 'big' | 'flow' | 'hit' | 'horn' | 'impact' | 'loop' | 'move' | 'splat' | 'ui' | 'weapon';
export type MusicCueId = 'lobby' | 'match' | 'final' | 'victory' | 'defeat';

export interface SfxEntry {
  /** variants: [start s, duration s] inside the sprite */
  readonly v: readonly (readonly [number, number])[];
  /** variant lengths in samples at the sprite rate (exact) */
  readonly n: readonly number[];
  readonly loop: boolean;
  readonly cat: SfxCategory;
  /** perceived level of the normalised take (dBFS RMS of its loudest 400 ms); the router levels by category */
  readonly ldb: number;
}
export interface MusicEntry {
  readonly url: string;
  readonly file: string;
  readonly seconds: number;
  readonly bytes: number;
  readonly kbps: number;
  /** [start s, duration s, samples] of each section (a pack loop, or the whole stinger) */
  readonly sections: readonly (readonly [number, number, number])[];
  /** played once, then `cycle` repeats (looping cues) */
  readonly intro: readonly number[];
  readonly cycle: readonly number[];
  readonly bpm: number;
  readonly loop: boolean;
  readonly lufs: number;
  readonly track: string;
}

export const SAMPLE_RATE = 44100;
/** s of wrap-around written before and after every loop region (seam.ts crossfades the head from it) */
export const SPRITE_GUARD_S = 0.06;
export const SFX_SPRITE = { url: new URL('./assets/sfx.ogg', import.meta.url).href, file: 'assets/sfx.ogg', seconds: 64.053129, samples: 2824743, bytes: 496572, kbps: 62.0 } as const;

export const SFX: { readonly [K in SfxId]: SfxEntry } = {
  ui_hover: { v: [[0.05, 0.011224]], n: [495], loop: false, cat: 'ui', ldb: -17.1 },
  ui_click: { v: [[0.111224, 0.211156]], n: [9312], loop: false, cat: 'ui', ldb: -19.8 },
  ui_back: { v: [[0.372381, 0.070136]], n: [3093], loop: false, cat: 'ui', ldb: -17.7 },
  ui_start: { v: [[0.492517, 0.524649]], n: [23137], loop: false, cat: 'ui', ldb: -13.9 },
  beep: { v: [[1.067166, 0.169819]], n: [7489], loop: false, cat: 'flow', ldb: -6.9 },
  beep_go: { v: [[1.286984, 0.319955]], n: [14110], loop: false, cat: 'flow', ldb: -6.1 },
  tick: { v: [[1.656939, 0.1]], n: [4410], loop: false, cat: 'flow', ldb: -17.8 },
  horn_start: { v: [[1.806939, 1.247891]], n: [55032], loop: false, cat: 'horn', ldb: -12.9 },
  horn_minute: { v: [[3.10483, 0.839138]], n: [37006], loop: false, cat: 'horn', ldb: -14.5 },
  horn_final: { v: [[3.993968, 0.617914]], n: [27250], loop: false, cat: 'horn', ldb: -13.1 },
  horn_end: { v: [[4.661882, 2.3939]], n: [105571], loop: false, cat: 'horn', ldb: -13.0 },
  special_ready: { v: [[7.105782, 1.21]], n: [53361], loop: false, cat: 'ui', ldb: -10.1 },
  tank_low: { v: [[8.365782, 0.479773]], n: [21158], loop: false, cat: 'ui', ldb: -12.0 },
  confirm: { v: [[8.895556, 0.312698]], n: [13790], loop: false, cat: 'ui', ldb: -14.5 },
  shot_mist: { v: [[9.258254, 0.136054], [9.444308, 0.135533], [9.629841, 0.135669]], n: [6000, 5977, 5983], loop: false, cat: 'weapon', ldb: -18.3 },
  shot_drum: { v: [[9.81551, 0.611565]], n: [26970], loop: false, cat: 'weapon', ldb: -13.5 },
  roll_loop: { v: [[10.537075, 1.2]], n: [52920], loop: true, cat: 'loop', ldb: -19.3 },
  flick: { v: [[11.847075, 0.497029]], n: [21919], loop: false, cat: 'weapon', ldb: -14.5 },
  shot_needle: { v: [[12.394104, 0.537438]], n: [23701], loop: false, cat: 'weapon', ldb: -15.5 },
  shot_pop: { v: [[12.981542, 0.32771]], n: [14452], loop: false, cat: 'weapon', ldb: -17.3 },
  burst: { v: [[13.359252, 0.737755], [14.147007, 0.69059]], n: [32535, 30455], loop: false, cat: 'impact', ldb: -18.9 },
  splat: { v: [[14.887596, 0.330476], [15.268073, 0.334331], [15.652404, 0.333946], [16.036349, 0.332358], [16.418707, 0.331995]], n: [14574, 14744, 14727, 14657, 14641], loop: false, cat: 'splat', ldb: -17.1 },
  dry: { v: [[16.800703, 0.063878]], n: [2817], loop: false, cat: 'ui', ldb: -14.3 },
  hit_dealt: { v: [[16.91458, 0.109773]], n: [4841], loop: false, cat: 'ui', ldb: -13.9 },
  hit_taken: { v: [[17.074354, 0.313651], [17.438005, 0.324739]], n: [13832, 14321], loop: false, cat: 'hit', ldb: -23.8 },
  washed_me: { v: [[17.812744, 1.602653]], n: [70677], loop: false, cat: 'big', ldb: -13.8 },
  washed: { v: [[19.465397, 0.791247]], n: [34894], loop: false, cat: 'impact', ldb: -18.5 },
  respawn: { v: [[20.306644, 1.257687]], n: [55464], loop: false, cat: 'impact', ldb: -13.5 },
  slick_in: { v: [[21.614331, 0.288549]], n: [12725], loop: false, cat: 'move', ldb: -14.7 },
  slick_out: { v: [[21.95288, 0.412086]], n: [18173], loop: false, cat: 'move', ldb: -17.7 },
  swim_loop: { v: [[22.474966, 3.0]], n: [132300], loop: true, cat: 'loop', ldb: -13.4 },
  refill_loop: { v: [[25.644966, 2.5]], n: [110250], loop: true, cat: 'loop', ldb: -19.6 },
  jump: { v: [[28.254966, 0.296213]], n: [13063], loop: false, cat: 'move', ldb: -15.1 },
  land: { v: [[28.601179, 0.099751], [28.75093, 0.104286], [28.905215, 0.108095]], n: [4399, 4599, 4767], loop: false, cat: 'move', ldb: -23.1 },
  land_hard: { v: [[29.063311, 0.569138]], n: [25099], loop: false, cat: 'move', ldb: -22.4 },
  sub_throw: { v: [[29.682449, 0.687732]], n: [30329], loop: false, cat: 'weapon', ldb: -15.3 },
  sub_land: { v: [[30.420181, 0.815034]], n: [35943], loop: false, cat: 'impact', ldb: -23.1 },
  sub_pop: { v: [[31.285215, 0.839274]], n: [37012], loop: false, cat: 'impact', ldb: -19.2 },
  cloud_throw: { v: [[32.17449, 1.672608]], n: [73762], loop: false, cat: 'weapon', ldb: -14.3 },
  thunder: { v: [[33.897098, 3.905034]], n: [172212], loop: false, cat: 'big', ldb: -20.5 },
  rain_loop: { v: [[37.912132, 4.0]], n: [176400], loop: true, cat: 'loop', ldb: -13.3 },
  leap: { v: [[42.022132, 0.741995]], n: [32722], loop: false, cat: 'weapon', ldb: -14.1 },
  slam: { v: [[42.814127, 1.538435]], n: [67845], loop: false, cat: 'big', ldb: -20.3 },
  spring: { v: [[44.402562, 0.590567]], n: [26044], loop: false, cat: 'impact', ldb: -13.6 },
  conveyor_loop: { v: [[45.103129, 2.5]], n: [110250], loop: true, cat: 'loop', ldb: -18.7 },
  amb_harbor: { v: [[47.773129, 8.0]], n: [352800], loop: true, cat: 'amb', ldb: -17.8 },
  amb_works: { v: [[55.943129, 8.0]], n: [352800], loop: true, cat: 'amb', ldb: -14.6 },
};

export const MUSIC: { readonly [K in MusicCueId]: MusicEntry } = {
  lobby: {
    url: new URL('./assets/music_lobby.ogg', import.meta.url).href, file: 'assets/music_lobby.ogg',
    seconds: 57.599955, bytes: 771825, kbps: 107.2,
    sections: [[0.0, 19.199955, 846718], [19.199955, 19.2, 846720], [38.399955, 19.2, 846720]],
    intro: [], cycle: [0, 1, 0, 1, 2, 1],
    bpm: 100, loop: true, lufs: -17.1, track: 'Revelation',
  },
  match: {
    url: new URL('./assets/music_match.ogg', import.meta.url).href, file: 'assets/music_match.ogg',
    seconds: 48.0, bytes: 633317, kbps: 105.6,
    sections: [[0.0, 16.0, 705600], [16.0, 32.0, 1411200]],
    intro: [], cycle: [0, 1],
    bpm: 120, loop: true, lufs: -16.1, track: 'Chasing The Stars',
  },
  final: {
    url: new URL('./assets/music_final.ogg', import.meta.url).href, file: 'assets/music_final.ogg',
    seconds: 41.141973, bytes: 582740, kbps: 113.3,
    sections: [[0.0, 13.713991, 604787], [13.713991, 13.713991, 604787], [27.427982, 13.713991, 604787]],
    intro: [], cycle: [0, 1, 2],
    bpm: 140, loop: true, lufs: -15.1, track: 'Hyper Drive',
  },
  victory: {
    url: new URL('./assets/music_victory.ogg', import.meta.url).href, file: 'assets/music_victory.ogg',
    seconds: 9.6, bytes: 127788, kbps: 106.5,
    sections: [[0.0, 9.6, 423360]],
    intro: [], cycle: [0],
    bpm: 100, loop: false, lufs: -15.0, track: 'Revelation',
  },
  defeat: {
    url: new URL('./assets/music_defeat.ogg', import.meta.url).href, file: 'assets/music_defeat.ogg',
    seconds: 9.6, bytes: 137321, kbps: 114.4,
    sections: [[0.0, 9.6, 423360]],
    intro: [], cycle: [0],
    bpm: 100, loop: false, lufs: -16.6, track: '8-bit Hero',
  },
};

/** every shipped audio byte (sprite + music), for the ≤ 8 MB budget */
export const AUDIO_PAYLOAD_BYTES = 2749563;
/** tracks registered for the slug `dyefield` in state/music_assignments.json */
export const REGISTERED_TRACKS = ['Travis Rise/SynthWave Music Pack/01_Revelation', 'Travis Rise/SynthWave Music Pack/02_ChasingTheStars', 'Travis Rise/SynthWave Music Pack/05_HyperDrive', 'Travis Rise/SynthWave Music Pack/06_8-bitHero'] as const;
