#!/usr/bin/env python
"""DYEFIELD — LOCKWELL WORKS geometric fairness + reachability QA (CONTRACT_ART_P6_8 §15).

Plain Python (numpy + scipy + PIL, no Blender). Reads the EXPORTED GLB, so it checks what the
runtime will load, not the layout's intent:

    python art/blender/lockwell_qa.py [art/gltf/map_lockwell.glb] [--out art/renders]

1. Collision soup = every mesh node prefixed paint_ solid_ grate_ conveyor_ spring_ col_ (node TRS
   applied; they are identity by contract). deco_ / water_ / oob_ never collide.
2. Voxelise at 0.15 m (x, z) x 0.10 m (y): `occ` = any collision triangle sample, `walk` = samples of
   triangles with n.y >= cos(46 deg) (config.ts MOVE.maxSlopeDeg).
3. STANDABLE = walk voxel whose capsule body (0.4 .. 1.2 m above it, radius 0.30 m) holds no
   collision sample (MOVE.radius 0.32, 1.15 m tall).
4. Moves: WALK to any 8-neighbour standable voxel within +-0.4 m (MOVE.stepHeight 0.35 + one voxel)
   both ways; DROP off a ledge onto the first surface below (one way). No jumps and NO wall-slick:
   every route found here is a walking route.
5. Flood from each spawn: every standable voxel must be reached from BOTH spawns, and must be able
   to walk back to that spawn (no one-way traps). Named areas get a route (the sequence of areas
   the shortest path walks through), path lengths are compared A vs B (rot180 fairness), spring_
   nodes get a ballistic check (g = 15 m/s^2) — Lockwell has none.
Writes <out>/map_lockwell_routes.json and <out>/map_lockwell_reach.png.
"""
from __future__ import annotations

import json
import math
import os
import struct
import sys
from collections import deque

import numpy as np
from scipy import ndimage

COLLIDE = ("paint_", "solid_", "grate_", "conveyor_", "spring_", "col_")
DX, DY = 0.15, 0.10
R_BODY = 0.30          # clearance radius used (capsule radius 0.32 minus half a cell of slack)
BODY_LO, BODY_HI = 0.4, 1.2
STEP_K = 4             # +-0.4 m per 0.15 m move
MIN_NY = math.cos(math.radians(46.0))
GRAVITY = 15.0

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.dirname(HERE)

# Named areas (glTF): (name, rot180 twin, (x0, x1), (z0, z1), (y0, y1)). First match wins, so
# connectors (stairs, ramps, conveyors) are matched before the floors they sit on. The twins are
# generated by rot180 (x, z) -> (-x, -z).
AREAS_A = [
    ("conveyor_A", "conveyor_B", (9.5, 13.0), (-24.0, -10.0), (-0.2, 4.8)),
    ("dock_ramp_A_w", "dock_ramp_B_e", (-6.5, -3.0), (-25.0, -21.0), (-0.2, 1.3)),
    ("dock_ramp_A_e", "dock_ramp_B_w", (3.0, 6.5), (-25.0, -21.0), (-0.2, 1.3)),
    ("corner_stair_SE", "corner_stair_NW", (13.4, 19.2), (-28.8, -25.0), (0.8, 4.8)),
    ("corner_stair_SW", "corner_stair_NE", (-19.2, -13.4), (-28.8, -25.0), (0.8, 4.8)),
    ("press_stair_W", "press_stair_E", (-7.2, -5.2), (-8.8, -3.5), (-0.2, 3.8)),
    ("upper_stair_A", "upper_stair_B", (19.2, 22.0), (-16.0, -8.4), (4.3, 9.3)),
    ("landing_SE", "landing_NW", (19.2, 22.0), (-28.8, -25.0), (4.3, 4.8)),
    ("landing_SW", "landing_NE", (-22.0, -19.2), (-28.8, -25.0), (4.3, 4.8)),
    ("press_top_W", "press_top_E", (-8.0, -3.5), (-3.5, 3.5), (3.3, 4.8)),
    ("office_E", "office_W", (17.3, 21.7), (-4.7, 4.7), (4.3, 5.0)),
    ("office_roof_E", "office_roof_W", (17.0, 22.0), (-5.0, 5.0), (8.8, 9.3)),
    ("winch_A", "winch_B", (17.0, 22.0), (-20.0, -16.0), (8.8, 9.3)),
    ("nest", "nest", (-3.2, 3.2), (-3.2, 3.2), (8.8, 9.3)),
    ("spine_S", "spine_N", (-1.1, 1.1), (-16.9, -3.2), (8.8, 9.3)),
    ("cross_S", "cross_N", (-1.1, 17.0), (-19.1, -16.9), (8.8, 9.3)),
    ("office_cw_E", "office_cw_W", (3.2, 17.0), (-1.1, 1.1), (8.8, 9.3)),
    ("bridge_S", "bridge_N", (-13.0, 13.0), (-10.0, -7.0), (4.3, 4.8)),
    ("gallery_E", "gallery_W", (13.0, 22.0), (-25.0, 25.0), (4.3, 4.8)),
    ("dock_alcove_SE", "dock_alcove_NW", (13.0, 22.0), (-32.0, -28.8), (0.8, 1.3)),
    ("dock_alcove_SW", "dock_alcove_NE", (-22.0, -13.0), (-32.0, -28.8), (0.8, 1.3)),
    ("dock_A", "dock_B", (-13.4, 13.4), (-32.0, -25.0), (0.8, 1.3)),
    ("hall_S", "hall_N", (-13.0, 13.0), (-25.0, 0.0), (-0.2, 0.3)),
]


def areas():
    """[(name, twin, (x0, x1), (z0, z1), (y0, y1))] for both halves, authored order (A half first)."""
    out = [a for a in AREAS_A]
    for (n, tw, (x0, x1), (z0, z1), yr) in AREAS_A:
        if tw != n:
            out.append((tw, n, (-x1, -x0), (-z1, -z0), yr))
    order = {a[0]: i for i, a in enumerate(AREAS_A)}
    return sorted(out, key=lambda a: order.get(a[0], order.get(a[1], 99)))


# ── GLB ──────────────────────────────────────────────────────────────────────────────────────────
def read_glb(path):
    data = open(path, "rb").read()
    magic, _, _ = struct.unpack_from("<III", data, 0)
    assert magic == 0x46546C67, "not a GLB"
    off = 12
    j = binc = None
    while off < len(data):
        ln, typ = struct.unpack_from("<II", data, off)
        chunk = data[off + 8: off + 8 + ln]
        if typ == 0x4E4F534A:
            j = json.loads(chunk.decode("utf-8"))
        elif typ == 0x004E4942:
            binc = chunk
        off += 8 + ln
    return j, binc


CT = {5120: np.int8, 5121: np.uint8, 5122: np.int16, 5123: np.uint16, 5125: np.uint32, 5126: np.float32}
NC = {"SCALAR": 1, "VEC2": 2, "VEC3": 3, "VEC4": 4, "MAT4": 16}


def accessor(j, binc, idx):
    a = j["accessors"][idx]
    bv = j["bufferViews"][a["bufferView"]]
    dt = np.dtype(CT[a["componentType"]])
    n = NC[a["type"]]
    start = bv.get("byteOffset", 0) + a.get("byteOffset", 0)
    stride = bv.get("byteStride", 0)
    if stride and stride != dt.itemsize * n:
        raw = np.frombuffer(binc, np.uint8, count=stride * a["count"], offset=start)
        arr = np.lib.stride_tricks.as_strided(raw, (a["count"], dt.itemsize * n), (stride, 1)).copy().view(dt)
        return arr.reshape(a["count"], n)
    return np.frombuffer(binc, dt, count=a["count"] * n, offset=start).reshape(a["count"], n)


def node_tris(j, binc, node):
    V, F = [], []
    base = 0
    for p in j["meshes"][node["mesh"]]["primitives"]:
        pos = accessor(j, binc, p["attributes"]["POSITION"]).astype(np.float64)
        idx = accessor(j, binc, p["indices"]).reshape(-1, 3).astype(np.int64) if "indices" in p else \
            np.arange(len(pos)).reshape(-1, 3)
        V.append(pos)
        F.append(idx + base)
        base += len(pos)
    V = np.concatenate(V)
    F = np.concatenate(F)
    t = node.get("translation")
    if t or node.get("rotation") or node.get("scale") or node.get("matrix"):
        raise SystemExit(f"{node['name']}: collision node has a transform (contract: identity)")
    return V, F


def sample_tris(V, F, spacing):
    """Points on every triangle (barycentric lattice, <= spacing apart) + the triangle normal's y."""
    A, B, Cc = V[F[:, 0]], V[F[:, 1]], V[F[:, 2]]
    n = np.cross(B - A, Cc - A)
    ln = np.linalg.norm(n, axis=1)
    ok = ln > 1e-12
    A, B, Cc, n, ln = A[ok], B[ok], Cc[ok], n[ok], ln[ok]
    ny = n[:, 1] / ln
    emax = np.maximum(np.maximum(np.linalg.norm(B - A, axis=1), np.linalg.norm(Cc - B, axis=1)), np.linalg.norm(A - Cc, axis=1))
    k = np.maximum(1, np.ceil(emax / spacing)).astype(np.int64)
    pts, nys = [], []
    for kk in np.unique(k):
        sel = np.nonzero(k == kk)[0]
        ii, jj = np.meshgrid(np.arange(kk + 1), np.arange(kk + 1), indexing="ij")
        m = (ii + jj) <= kk
        u = (ii[m] / kk)[None, :, None]
        v = (jj[m] / kk)[None, :, None]
        P = A[sel][:, None, :] + (B[sel] - A[sel])[:, None, :] * u + (Cc[sel] - A[sel])[:, None, :] * v
        pts.append(P.reshape(-1, 3))
        nys.append(np.repeat(ny[sel], m.sum()))
    return np.concatenate(pts), np.concatenate(nys)


# ── voxel graph ──────────────────────────────────────────────────────────────────────────────────
class Grid:
    def __init__(self, lo, hi):
        self.lo = np.array(lo, np.float64)
        self.shape = tuple(int(math.ceil((hi[i] - lo[i]) / (DX if i != 1 else DY))) + 1 for i in range(3))

    def idx(self, p):
        p = np.asarray(p, np.float64)
        return np.floor((p - self.lo) / np.array([DX, DY, DX])).astype(np.int64)

    def pos(self, i, j, k):
        return (self.lo[0] + (i + 0.5) * DX, self.lo[1] + (j + 1.0) * DY, self.lo[2] + (k + 0.5) * DX)


def ray_blocked(tris, o, d, tmax):
    """Möller-Trumbore against every collision triangle: True if the segment o -> o + d*tmax hits."""
    A, B, Cc = tris
    e1, e2 = B - A, Cc - A
    p = np.cross(d, e2)
    det = (e1 * p).sum(1)
    ok = np.abs(det) > 1e-12
    inv = np.zeros_like(det)
    inv[ok] = 1.0 / det[ok]
    tv = o - A
    u = (tv * p).sum(1) * inv
    q = np.cross(tv, e1)
    v = (q * d).sum(1) * inv
    t = (q * e2).sum(1) * inv
    hit = ok & (u >= 0) & (v >= 0) & (u + v <= 1) & (t > 1e-3) & (t < tmax - 1e-3)
    return bool(hit.any())


def sightlines(soup, spawns):
    """Can a charger at the crane nest / the spine ends see a spawn pad? Eye = feet + 1.35 m on a
    grid over the perch; targets = chest height (feet + 1.0) on a grid over each pad (r 2.0)."""
    V = [v[f] for v, f in ((v, F) for v, F in soup)]
    A = np.concatenate([v[f[:, 0]] for v, f in soup])
    B = np.concatenate([v[f[:, 1]] for v, f in soup])
    Cc = np.concatenate([v[f[:, 2]] for v, f in soup])
    tris = (A, B, Cc)
    perches = {
        "nest": [(x, 9.0 + 1.35, z) for x in (-2.4, -1.2, 0.0, 1.2, 2.4) for z in (-2.6, -1.3, 0.0, 1.3, 2.6)],
        "spine_end_S": [(x, 9.0 + 1.35, z) for x in (-0.7, 0.0, 0.7) for z in (-18.8, -17.8, -16.5)],
        "spine_end_N": [(x, 9.0 + 1.35, z) for x in (-0.7, 0.0, 0.7) for z in (16.5, 17.8, 18.8)],
    }
    out = {}
    for side, sp in sorted(spawns.items()):
        tg = [(sp[0] + dx, sp[1] + 1.0, sp[2] + dz) for dx in (-1.6, -0.8, 0.0, 0.8, 1.6) for dz in (-1.6, -0.8, 0.0, 0.8, 1.6)
              if dx * dx + dz * dz <= 4.0]
        for pname, eyes in perches.items():
            vis = tot = 0
            for e in eyes:
                for t in tg:
                    o = np.array(e, np.float64)
                    dvec = np.array(t, np.float64) - o
                    L = float(np.linalg.norm(dvec))
                    tot += 1
                    if not ray_blocked(tris, o, dvec / L, L):
                        vis += 1
            out[f"{pname}->pad_{side}"] = {"rays": tot, "clear": vis, "pct_clear": round(100.0 * vis / tot, 1)}
    return out


def build_graph(soup, gl, gh):
    g = Grid(gl, gh)
    X, Y, Z = g.shape
    occ = np.zeros((X, Y, Z), bool)
    walk = np.zeros((X, Y, Z), bool)
    for (V, F) in soup:
        P, ny = sample_tris(V, F, 0.06)
        I = g.idx(P)
        keep = (I >= 0).all(1) & (I[:, 0] < X) & (I[:, 1] < Y) & (I[:, 2] < Z)
        I, ny = I[keep], ny[keep]
        occ[I[:, 0], I[:, 1], I[:, 2]] = True
        w = ny >= MIN_NY
        walk[I[w, 0], I[w, 1], I[w, 2]] = True
    # capsule body clearance: any occupancy within R_BODY (xz disk) between +0.4 and +1.2 m
    r = int(round(R_BODY / DX))
    yy, xx = np.mgrid[-r:r + 1, -r:r + 1]
    disk = (xx * xx + yy * yy) <= r * r + 0.01
    st = np.zeros((2 * r + 1, 1, 2 * r + 1), bool)
    st[:, 0, :] = disk
    occ_d = ndimage.binary_dilation(occ, structure=st)
    k0, k1 = int(round(BODY_LO / DY)), int(round(BODY_HI / DY))
    cs = np.concatenate([np.zeros((X, 1, Z), np.int32), np.cumsum(occ_d, axis=1, dtype=np.int32)], axis=1)
    body = np.zeros((X, Y, Z), bool)
    for kk in range(Y):
        a, b = min(Y, kk + k0), min(Y, kk + k1 + 1)
        if a < b:
            body[:, kk, :] = (cs[:, b, :] - cs[:, a, :]) > 0
    # support: >= 7 of the 3x3 columns around must carry walkable surface within 0.2 m below
    # (a 1.15 m capsule cannot balance on a 7 cm rail or a 30 cm parapet top)
    sup = np.zeros((X, Y, Z), bool)
    wk = walk | np.concatenate([walk[:, 1:, :], np.zeros((X, 1, Z), bool)], axis=1) |         np.concatenate([np.zeros((X, 1, Z), bool), walk[:, :-1, :]], axis=1) |         np.concatenate([np.zeros((X, 2, Z), bool), walk[:, :-2, :]], axis=1)
    cnt = ndimage.convolve(wk.astype(np.uint8), np.ones((3, 1, 3), np.uint8), mode="constant")
    sup = cnt >= 7
    stand = walk & ~body & sup
    # keep only the top voxel of a vertical run of standable voxels (one node per surface)
    top = stand & ~np.concatenate([stand[:, 1:, :], np.zeros((X, 1, Z), bool)], axis=1)
    return g, occ, stand, top


def edges(g, occ, top):
    X, Y, Z = top.shape
    ids = -np.ones(top.shape, np.int64)
    nodes = np.argwhere(top)
    ids[nodes[:, 0], nodes[:, 1], nodes[:, 2]] = np.arange(len(nodes))
    # highest `top` voxel at or below each level (for drops) and the highest occupied voxel at or below
    lev = np.arange(Y)[None, :, None]
    below_top = np.maximum.accumulate(np.where(top, lev, -1), axis=1)
    below_occ = np.maximum.accumulate(np.where(occ, lev, -1), axis=1)
    src, dst, kind = [], [], []
    dirs = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, 1), (1, -1), (-1, 1), (-1, -1)]
    i, j, k = nodes[:, 0], nodes[:, 1], nodes[:, 2]
    for (di, dk) in dirs:
        ii, kk = i + di, k + dk
        inb = (ii >= 0) & (ii < X) & (kk >= 0) & (kk < Z)
        has_walk = np.zeros(len(nodes), bool)
        for dj in range(-STEP_K, STEP_K + 1):
            jj = j + dj
            ok = inb & (jj >= 0) & (jj < Y)
            t = np.full(len(nodes), -1, np.int64)
            t[ok] = ids[ii[ok], jj[ok], kk[ok]]
            m = t >= 0
            src.append(np.nonzero(m)[0])
            dst.append(t[m])
            kind.append(np.zeros(m.sum(), np.int8))
            has_walk |= m
        # drop: walk off a ledge. The capsule leaves the ledge once its centre is ~one radius past the
        # edge, so the landing column is looked for 1..3 cells out (0.15 - 0.45 m); it falls onto
        # the first collision surface under it, which must be standable (not a rail, not a wall top)
        for sd in (1, 2, 3):
            i2, k2 = i + di * sd, k + dk * sd
            ok = (i2 >= 0) & (i2 < X) & (k2 >= 0) & (k2 < Z) & (j - STEP_K - 1 >= 0)
            c = np.nonzero(ok)[0]
            jb = np.full(len(nodes), -1, np.int64)
            jo = np.full(len(nodes), -1, np.int64)
            jb[c] = below_top[i2[c], j[c] - STEP_K - 1, k2[c]]
            jo[c] = below_occ[i2[c], np.minimum(j[c] + STEP_K + 2, Y - 1), k2[c]]
            m = ok & (jb >= 0) & (jo >= 0) & (np.abs(jo - jb) <= 1)
            mi = np.nonzero(m)[0]
            src.append(mi)
            dst.append(ids[i2[mi], jb[mi], k2[mi]])
            kind.append(np.ones(len(mi), np.int8))
    src = np.concatenate(src)
    dst = np.concatenate(dst)
    kind = np.concatenate(kind)
    ok = dst >= 0
    return nodes, ids, src[ok], dst[ok], kind[ok]


def bfs(n, src, dst, start, reverse=False):
    a, b = (dst, src) if reverse else (src, dst)
    order = np.argsort(a, kind="stable")
    a, b = a[order], b[order]
    ptr = np.searchsorted(a, np.arange(n + 1))
    dist = np.full(n, -1, np.int64)
    par = np.full(n, -1, np.int64)
    dist[start] = 0
    q = deque([start])
    while q:
        u = q.popleft()
        for v in b[ptr[u]:ptr[u + 1]]:
            if dist[v] < 0:
                dist[v] = dist[u] + 1
                par[v] = u
                q.append(v)
    return dist, par


def main(argv):
    glb = os.path.join(ART, "gltf", "map_lockwell.glb")
    out = os.path.join(ART, "renders")
    rest = list(argv)
    if "--out" in rest:
        k = rest.index("--out")
        out = rest[k + 1]
        del rest[k:k + 2]
    if rest:
        glb = rest[0]
    j, binc = read_glb(glb)
    nodes_json = j["nodes"]
    soup, springs, conveyors = [], [], {}
    for nd in nodes_json:
        nm = nd.get("name", "")
        if "mesh" in nd and nm.startswith(COLLIDE):
            soup.append(node_tris(j, binc, nd))
        if nm.startswith("spring_"):
            springs.append((nm, (nd.get("extras") or {}).get("df_launch")))
        if nm.startswith("conveyor_"):
            conveyors[nm] = (nd.get("extras") or {}).get("df_conveyor")
    spawns = {}
    for nd in nodes_json:
        if nd.get("name") in ("spawn_A", "spawn_B"):
            spawns[nd["name"][-1]] = nd.get("translation", [0, 0, 0])
    allv = np.concatenate([v for v, _ in soup])
    lo = allv.min(0) - 0.3
    hi = allv.max(0) + 0.3
    g, occ, stand, top = build_graph(soup, lo, hi)
    roof_y = 12.9                                      # the roof underside is at 13.0 (bounds.max.y)
    nodes, ids, src, dst, kind = edges(g, occ, top)
    n = len(nodes)
    P = np.array([g.pos(*nd) for nd in nodes])

    def nearest(p):
        d = np.linalg.norm(P - np.array(p), axis=1)
        return int(np.argmin(d)), float(d.min())
    res = {"glb": os.path.relpath(glb, os.path.dirname(ART)).replace("\\", "/"), "voxel": [DX, DY, DX],
           "standable_nodes": n, "walk_edges": int((kind == 0).sum()), "drop_edges": int((kind == 1).sum()),
           "rules": {"walk_step_m": STEP_K * DY, "max_slope_deg": 46, "body": [BODY_LO, BODY_HI, R_BODY],
                     "wall_slick": "never used", "jumps": "never used"}}
    reach, back, par = {}, {}, {}
    for side, p in sorted(spawns.items()):
        s, d = nearest(p)
        res[f"spawn_{side}"] = {"pos": [round(c, 3) for c in p], "node": [round(c, 2) for c in P[s]], "snap_m": round(d, 3)}
        reach[side], par[side] = bfs(n, src, dst, s)
        back[side], _ = bfs(n, src, dst, s, reverse=True)
    # label every node with its area
    labels = np.full(n, -1, np.int64)
    alist = areas()
    for ai, (name, _tw, (x0, x1), (z0, z1), (y0, y1)) in enumerate(alist):
        m = (labels < 0) & (P[:, 0] >= x0 - 0.05) & (P[:, 0] <= x1 + 0.05) & (P[:, 2] >= z0 - 0.05) & \
            (P[:, 2] <= z1 + 0.05) & (P[:, 1] >= y0) & (P[:, 1] <= y1)
        labels[m] = ai
    # unlabelled standable surfaces (crate tops, rail tops ...) keep label -1 = "other"

    def route(side, target):
        """Area names along the BFS path (walk + drop edges), and the path length in metres."""
        seq, length = [], 0.0
        v = target
        prev = None
        while v >= 0:
            lab = alist[labels[v]][0] if labels[v] >= 0 else "other"
            if not seq or seq[-1] != lab:
                seq.append(lab)
            if prev is not None:
                length += float(np.linalg.norm(P[v] - P[prev]))
            prev = v
            v = par[side][v]
        seq = list(reversed(seq))
        seq = [x for i, x in enumerate(seq) if x != "other" or i in (0, len(seq) - 1)]
        seq = [x for i, x in enumerate(seq) if i == 0 or x != seq[i - 1]]
        return seq, length
    table = {}
    step_m = DX
    for ai, (name, _tw, (x0, x1), (z0, z1), yr) in enumerate(alist):
        members = np.nonzero(labels == ai)[0]
        row = {"nodes": int(len(members))}
        if len(members) == 0:
            row["error"] = "no standable surface found"
            table[name] = row
            continue
        c = np.array([(x0 + x1) / 2, (yr[0] + yr[1]) / 2, (z0 + z1) / 2])
        for side in sorted(spawns):
            r = reach[side][members]
            b = back[side][members]
            row[f"reach_{side}"] = round(float((r >= 0).mean()), 4)
            row[f"back_{side}"] = round(float((b >= 0).mean()), 4)
            ok = members[r >= 0]
            if len(ok):
                t = ok[np.argmin(np.linalg.norm(P[ok] - c, axis=1))]
                seq, length = route(side, t)
                row[f"route_{side}"] = seq
                row[f"path_m_{side}"] = round(length, 1)
                row[f"walk_s_{side}"] = round(length / 5.2, 1)
        table[name] = row
    res["areas"] = table
    # global checks
    for side in sorted(spawns):
        res[f"unreached_from_{side}"] = int((reach[side] < 0).sum())
        res[f"one_way_traps_{side}"] = int(((reach[side] >= 0) & (back[side] < 0)).sum())
    # tiny unreached pockets: report their bounding boxes (crate tops, rail tops, wedge slivers)
    unreached = np.nonzero((reach["A"] < 0) | (reach["B"] < 0))[0]
    lab_img = np.zeros(len(nodes), np.int64)
    pockets = []
    if len(unreached):
        mask = np.zeros(top.shape, bool)
        mask[nodes[unreached, 0], nodes[unreached, 1], nodes[unreached, 2]] = True
        lbl, nl = ndimage.label(mask, structure=np.ones((3, 3, 3), bool))
        for li in range(1, nl + 1):
            pts = np.argwhere(lbl == li)
            wp = np.array([g.pos(*p) for p in pts])
            area = len(pts) * DX * DX
            what = [alist[labels[ids[p[0], p[1], p[2]]]][0] if labels[ids[p[0], p[1], p[2]]] >= 0 else "other" for p in pts[:1]][0]
            pockets.append({"area_m2": round(area, 2), "min": [round(v, 2) for v in wp.min(0)],
                            "max": [round(v, 2) for v in wp.max(0)], "label": what})
        pockets.sort(key=lambda d: -d["area_m2"])
    res["unreached_pockets"] = pockets[:40]
    res["unreached_pockets_total_m2"] = round(sum(p["area_m2"] for p in pockets), 2)
    inside = [p for p in pockets if p["max"][1] < roof_y]
    res["unreached_inside_building_m2"] = round(sum(p["area_m2"] for p in inside), 2)
    res["unreached_inside_note"] = ("tops that need a jump or are not play space: canopy roofs 6.0, crane-cab roof 11.8, "
                                    "press crowns 6.9-7.1, crate tops, parapet / rail tops; none is paintable floor")
    # rot180 fairness: A -> area vs B -> its twin
    fair = []
    for (name, tw, _, _, _) in AREAS_A:
        a, b = table.get(name, {}), table.get(tw, {})
        if "path_m_A" in a and "path_m_B" in b:
            fair.append({"area": name, "twin": tw, "A_m": a["path_m_A"], "B_m": b["path_m_B"],
                         "delta_m": round(abs(a["path_m_A"] - b["path_m_B"]), 1)})
    res["fairness_A_vs_B_twin"] = fair
    res["fairness_max_delta_m"] = max((f["delta_m"] for f in fair), default=None)
    # springs (ballistic arcs) and conveyors
    res["springs"] = [{"node": nm, "df_launch": v} for nm, v in springs] or "none (LOCKWELL has no spring_ nodes)"
    conv = {}
    for nm, v in conveyors.items():
        sp = math.sqrt(sum(c * c for c in v))
        conv[nm] = {"df_conveyor": v, "speed": round(sp, 3), "walk_against_net_mps": round(5.2 - sp, 2),
                    "trap": (5.2 - sp) <= 0.0}
    res["conveyors"] = conv
    res["sightlines_to_spawn_pads"] = sightlines(soup, spawns)
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "map_lockwell_routes.json"), "w", encoding="utf-8") as f:
        json.dump(res, f, indent=1)
    # top-down picture: highest standable surface per column, coloured by floor; unreached = red
    try:
        from PIL import Image
        X, Y, Z = top.shape
        img = np.zeros((Z, X, 3), np.uint8)
        img[:] = (22, 26, 36)
        # reached surfaces are drawn over unreached ones (the outer roof, canopy and crane-cab tops are
        # unreachable by design); among reached surfaces the highest wins, like the minimap
        okA, okB = reach["A"] >= 0, reach["B"] >= 0
        bad = ~(okA & okB)
        trap = (okA & okB) & ((back["A"] < 0) | (back["B"] < 0))
        for v in np.nonzero(bad & (P[:, 1] < roof_y))[0]:      # the outer roof top is not play space
            i, _, k = nodes[v]
            img[k, i] = (235, 40, 40)
        good = np.nonzero(~bad)[0]
        for v in good[np.argsort(P[good, 1], kind="stable")]:
            i, _, k = nodes[v]
            y = P[v, 1]
            if trap[v]:
                col = (255, 0, 255)
            elif y < 0.6:
                col = (170, 170, 162)
            elif y < 2.3:
                col = (150, 168, 182) if y < 1.4 else (205, 150, 95)
            elif y < 4.2:
                col = (95, 190, 120)
            elif y < 7.6:
                col = (92, 190, 235)
            else:
                col = (255, 96, 170)
            img[k, i] = col
        img = img[::-1, ::-1]          # SUNCREW (-Z) at the bottom, screen-right = -X (minimap convention)
        for side, p in spawns.items():
            ii, _, kk = g.idx(p)
            cy, cx = Z - 1 - kk, X - 1 - ii
            img[max(0, cy - 4):cy + 5, max(0, cx - 4):cx + 5] = (255, 138, 31) if side == "A" else (91, 75, 240)
        Image.fromarray(img).resize((X * 3, Z * 3), Image.NEAREST).save(os.path.join(out, "map_lockwell_reach.png"))
    except ImportError:
        pass
    print(json.dumps({k: v for k, v in res.items() if k not in ("areas", "fairness_A_vs_B_twin", "unreached_pockets")}, indent=1))
    return res


if __name__ == "__main__":
    main(sys.argv[1:])
