// Single source of truth for the public site's identity and SEO defaults.
// Imported by the Vike config, the per-page head code and (as plain strings)
// mirrored by scripts/build-seo.mjs, which cannot import TypeScript. If you
// change SITE_URL here, change it in scripts/build-seo.mjs too.

export const SITE_URL = "https://forgeflowgames.com";
export const SITE_NAME = "ForgeFlow Games";

export const DEFAULT_TITLE = "ForgeFlow Games — Free Online Browser Games, Play Instantly";
export const DEFAULT_DESCRIPTION =
  "Play free browser games instantly — action, strategy, RPG, board games and more. No downloads, no installs, just click and play on ForgeFlow Games.";

// 1200x630, generated by scripts/make-og-image.py into public/images/.
export const DEFAULT_OG_IMAGE = `${SITE_URL}/images/og-default.png`;

/** Absolute URL for a path or an already-absolute URL. */
export function absUrl(pathOrUrl: string): string {
  if (!pathOrUrl) return DEFAULT_OG_IMAGE;
  if (/^https?:\/\//i.test(pathOrUrl)) return pathOrUrl;
  return SITE_URL + (pathOrUrl.startsWith("/") ? "" : "/") + pathOrUrl;
}

/**
 * Canonical URL for a request path: the site serves every page with a trailing
 * slash (Cloudflare 308s `/privacy` -> `/privacy/`), so the canonical must too,
 * or crawlers see two URLs per page. Query strings and hashes are dropped.
 */
export function canonicalFor(urlPathname: string): string {
  let p = (urlPathname || "/").split("?")[0].split("#")[0];
  if (!p.startsWith("/")) p = "/" + p;
  if (!p.endsWith("/")) p += "/";
  return SITE_URL + p;
}

/** Trim to a search-snippet-sized sentence boundary where possible. */
export function clip(text: string | null | undefined, max = 155): string {
  const t = (text || "").replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max - 1);
  const stop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("! "), cut.lastIndexOf("? "));
  if (stop > max * 0.55) return cut.slice(0, stop + 1);
  const sp = cut.lastIndexOf(" ");
  return (sp > max * 0.55 ? cut.slice(0, sp) : cut).replace(/[,;:\-–—\s]+$/, "") + "…";
}

/** Paths that must never be indexed (private, per-user or transient pages). */
export const NOINDEX_PREFIXES = ["/auth", "/profile", "/friends", "/search"];

export function isNoindex(urlPathname: string): boolean {
  const p = (urlPathname || "/").toLowerCase();
  return NOINDEX_PREFIXES.some((n) => p === n || p.startsWith(n + "/"));
}
