"""build_order.py — Layer-3 vertical-slice-first build orchestration.

Replaces the old "generate the whole game then check it runs" with:
    select-engine -> SLICE (1 mission, signature mechanic) -> [GATE] ->
    expand content -> [GATE] -> assemble -> (feel/fidelity)

Content is generated by claude -p as a JSON object that must validate against the
genre schema (so the design can't promise mechanics the engine can't express).
The schema + learned rules are injected into the prompt.

`claude -p` cannot run inside an interactive Claude session (OAuth lock, see
CLAUDE.md), so this module is split:
  - assemble(slug, genre, content) and gate runs work fully offline / now.
  - --dry-run <content.json>: assemble + gate an existing (hand-authored) content
    object end-to-end — proves the whole wiring without generation.
  - --slice-prompt / --expand-prompt <design.json>: print the exact claude -p
    prompt the operator (or Task Scheduler) runs to generate content.

Usage:
    python build_order.py --dry-run ../../games/rift-tactics/content.json
    python build_order.py --slice-prompt tactics "Hold the breach"   # prints prompt
    python build_order.py --assemble <slug> <content.json>           # build game folder
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parent
RUNTIME = ENGINE / "runtime"
GAMES = ENGINE.parent.parent / "games"
ASSETS = ENGINE.parent / "assets"
PIRATE_KIT = ASSETS / "_downloaded" / "pirate-kit" / "Models" / "GLB format"
REGISTRY = json.loads((ENGINE / "registry.json").read_text(encoding="utf-8"))


def _is_3d(prof):
    return prof.get("track") == "3d" or prof.get("renderer") == "three"

sys.path.insert(0, str(ENGINE))
import learn  # noqa: E402

GOLDEN = ENGINE / "golden"


def golden_seed(genre, item):
    """HIGH-BASELINE START: if a genre has a GOLDEN template (a polished, fully
    gated reference game snapshotted under engine/golden/<genre>.content.json),
    start a NEW game from it instead of a weak from-scratch LLM slice. Re-themes
    slug/title/seed; everything else (the polished maps/systems/audio) comes in at
    the high bar, and the autopipe improves from there. Returns content or None."""
    p = GOLDEN / f"{genre}.content.json"
    if not p.exists():
        return None
    try:
        c = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None
    if item.get("slug"):
        c["slug"] = item["slug"]
    if item.get("title"):
        c["title"] = item["title"]
    if item.get("seed") is not None:
        c["seed"] = item["seed"]
    c["_from_golden"] = True
    return c


def genre_profile(genre):
    g = REGISTRY["genres"].get(genre)
    if not g:
        raise SystemExit(f"[build_order] unknown genre '{genre}'. Known: {list(REGISTRY['genres'])}")
    return g


# ── Self-healing repair (deterministic) ──────────────────────────────────────
# Auto-fixes the recoverable failure classes the live run hit, so the autonomous
# loop fills/fixes and CONTINUES instead of stopping. Idempotent — safe to run
# after every generation step.
_VIEW_ALLOWED = {"width", "height", "background", "pixelArt", "fog"}


def repair(content, *, slug, genre, title=None):
    content.setdefault("slug", slug)
    content.setdefault("genre", genre)
    content.setdefault("title", title or slug.replace("-", " ").title())
    is3d = _is_3d(genre_profile(genre))
    # view: keep only schema-allowed keys; ensure required dims (the model loves
    # to emit view:{camera,zoom,lookAt} — the engine owns the camera).
    v = content.get("view") if isinstance(content.get("view"), dict) else {}
    clean = {k: v[k] for k in v if k in _VIEW_ALLOWED}
    clean.setdefault("width", 1024 if is3d else 960)
    clean.setdefault("height", 640 if is3d else 600)
    content["view"] = clean
    if genre in ("tactics", "tactics3d"):
        _repair_tactics_placements(content)
    return content


def _nearest_free_floor(grid, x, y, occupied, W, H):
    best, bestd = None, 10 ** 9
    for yy in range(H):
        row = grid[yy]
        for xx in range(min(W, len(row))):
            if row[xx] == 0 and (xx, yy) not in occupied:
                d = abs(xx - x) + abs(yy - y)
                if d < bestd:
                    bestd, best = d, (xx, yy)
    return best


def _repair_tactics_placements(content):
    """Move any unit off a wall(1)/full-cover(3)/out-of-bounds/overlapping tile
    onto the nearest free floor(0) tile. This is the auto-fix that turns the
    void-skirmish 'enemy spawned in cover' failure into a clean build."""
    for m in content.get("missions", []):
        grid = m.get("grid")
        if not grid:
            continue
        H = len(grid)
        W = len(grid[0]) if H else 0
        occupied = set()
        for side in ("player_units", "enemy_units"):
            for u in m.get(side, []):
                x, y = u.get("x"), u.get("y")
                in_bounds = isinstance(x, int) and isinstance(y, int) and 0 <= y < H and 0 <= x < W
                blocked = in_bounds and grid[y][x] in (1, 3)
                overlap = (x, y) in occupied
                if (not in_bounds) or blocked or overlap:
                    nf = _nearest_free_floor(grid, x if in_bounds else 0, y if in_bounds else 0, occupied, W, H)
                    if nf:
                        u["x"], u["y"] = nf
                occupied.add((u.get("x"), u.get("y")))


# ── Prompt construction (the constrained generator) ──────────────────────────
def slice_prompt(genre, brief):
    prof = genre_profile(genre)
    schema = (ENGINE / prof["schema"]).read_text(encoding="utf-8")
    rules = learn.prompt_block(genre)
    return f"""You are generating CONTENT (data, not engine code) for a browser game on the
ForgeFlow v2 engine. Genre: {genre} ({prof['label']}).
Brief: {brief}

Output ONLY a single JSON object that VALIDATES against this schema. Generate just
the FIRST mission (the vertical slice) — one tight, winnable encounter that fully
exercises the signature mechanic: {prof['signature_mechanic']}.
Do not invent fields outside the schema. Use original IP (no trademarked names).

HARD REQUIREMENTS (these caused real rejections — obey exactly):
  - Top-level MUST include: "title" (string), "slug" ("{genre}"-style kebab), "genre".
  - "view" MUST be exactly {{"width": <int 240-1920>, "height": <int 180-1080>}}
    (plus optional "background"/"pixelArt"/"fog"). Do NOT put camera/zoom/lookAt
    in "view" — the engine owns the camera.
  - Tactics: EVERY unit (player AND enemy) MUST spawn on a floor tile (0). NEVER
    place a unit on a wall (1) or full-cover (3) tile. Verify each (x,y) before output.
  - Every map must be winnable and every enemy reachable.

SCHEMA:
{schema}

{rules}

Return only the JSON object."""


def expand_prompt(genre, content):
    prof = genre_profile(genre)
    rules = learn.prompt_block(genre)
    return f"""The vertical slice below passed all gates. Generate 4-6 ADDITIONAL missions of
escalating difficulty for this {genre} game, same schema, same signature mechanic
({prof['signature_mechanic']}). Keep units/cover varied; ensure every mission is
winnable and every unit spawns on a walkable tile.

{rules}

CURRENT CONTENT:
{json.dumps(content, indent=2)}

Return ONLY the full updated JSON object (slice + new missions)."""


def run_claude_p(prompt, timeout=300):
    """Run claude -p (NON-interactive contexts only). Returns parsed JSON or raises.
    Prompt via STDIN — Windows argv caps at 32,767 chars (WinError 206 on big prompts)."""
    out = subprocess.run(["claude", "-p"], input=prompt, capture_output=True, text=True,
                         encoding="utf-8", errors="replace", timeout=timeout)
    raw = (out.stdout or "").strip()
    s, e = raw.find("{"), raw.rfind("}")
    if s < 0 or e <= s:
        raise RuntimeError("no JSON in claude -p output: " + raw[:300])
    return json.loads(raw[s:e + 1])


# ── Gates ─────────────────────────────────────────────────────────────────────
def gate_content(content_path, genre):
    c = subprocess.run([sys.executable, str(ENGINE / "gates" / "contract_gate.py"), str(content_path)],
                       capture_output=True, text=True)
    s = subprocess.run(["node", str(ENGINE / "gates" / "signature_gate.cjs"), str(content_path), genre],
                       capture_output=True, text=True)
    return (c.returncode == 0 and s.returncode == 0), c.stdout.strip(), s.stdout.strip()


# ── Assemble ──────────────────────────────────────────────────────────────────
def assemble(slug, content):
    """Write the game folder: copy the pinned runtime, write content.json + index.html.
    Branches 2D (Phaser classic scripts) vs 3D (three.js ESM + importmap)."""
    genre = content["genre"]
    prof = genre_profile(genre)
    is3d = _is_3d(prof)
    gdir = GAMES / slug
    (gdir / "runtime" / "sim").mkdir(parents=True, exist_ok=True)
    # Every game gets the standard shell (menu/pause/win-lose/music).
    # 2D needs the classic loader + VERSION; 3D boots via its own ESM entry.
    needed = set(prof["runtime"]) | {"ffg_shell.js"}
    if not is3d:
        needed |= {"ffg_loader.js", "VERSION"}
    for rel in sorted(needed):
        src = RUNTIME / rel
        if not src.exists():
            print(f"[build_order] WARN missing runtime file {rel} (genre '{genre}' not built yet)")
            continue
        dst = gdir / "runtime" / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    if is3d:
        _copy_3d_assets(gdir, content)
        _copy_creature_assets(gdir, content)  # bundle CREATURES_INDEX models the content requests
    if genre in ("tactics", "tactics3d"):
        _copy_tactics_assets(gdir)
    # page-level control bar (Fullscreen / Mute / Pause) — every game ships with it
    _gc = RUNTIME / "game_controls.js"
    if _gc.exists():
        shutil.copy2(_gc, gdir / "game_controls.js")
    (gdir / "content.json").write_text(json.dumps(content, indent=2), encoding="utf-8")
    if genre == "tactics3d":
        _structure_tactics_maps(gdir / "content.json")  # XCOM parcel/plot — 3D ONLY (a 2D top-down camera fits the whole grid, so big parcel maps make units tiny; 2D tactics keeps small readable grids)
    (gdir / "index.html").write_text(_index_html_3d(content, prof) if is3d else _index_html_2d(content, prof), encoding="utf-8")
    return gdir


def _structure_tactics_maps(content_path):
    """Restructure a tactics game's maps onto the deterministic parcel/plot model
    (XCOM-style: a road network divides each plot into lots — enterable multi-room
    buildings, walled compounds, plazas, parks — with dense clustered cover) so
    tactics games never ship as flat, hand-drawn LLM grids. Preserves each
    mission's name/objective/goal, squad, and enemy stats; only the GRID + unit
    positions are regenerated, and connectivity is verified before write.
    Defensive: any failure (no node, tool missing, connectivity abort) leaves the
    already-written content.json untouched and the build continues."""
    tool = ENGINE / "tools" / "gen_campaign.cjs"
    if not tool.exists():
        print("[build_order] WARN gen_campaign.cjs missing — tactics maps left as-is")
        return
    try:
        r = subprocess.run(["node", str(tool), "--regen", str(content_path)],
                           capture_output=True, text=True, timeout=120)
        if r.returncode == 0:
            print("[build_order] tactics maps restructured onto the parcel/plot model:")
            for line in (r.stdout or "").strip().splitlines()[-8:]:
                print("   " + line)
        else:
            print(f"[build_order] WARN tactics map regen rc={r.returncode} — keeping existing maps\n{(r.stderr or '')[:300]}")
    except Exception as e:
        print(f"[build_order] WARN tactics map regen skipped ({e}) — keeping existing maps")


def _copy_tactics_assets(gdir):
    """Bundle the tactics unit-class icons (recolored white game-icons SVGs) so
    the renderer draws real unit silhouettes instead of lettered circles."""
    src = RUNTIME / "tactics-assets"
    if src.is_dir():
        for f in src.rglob("*"):
            if f.is_file():
                rel = f.relative_to(src)
                dst = gdir / "assets" / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, dst)
    # Bundle the rigged CHARACTER models (soldiers + aliens/robots/mech) and the
    # real CC0 CITY model set (walls/cover/buildings/furniture/decor + their
    # per-kit colormap subfolders) so a fresh tactics build renders real models,
    # not boxes — these ride next to the renderer under runtime/3d/.
    for sub in ("characters", "city"):
        msrc = RUNTIME / "3d" / sub
        if not msrc.is_dir():
            continue
        for f in msrc.rglob("*"):
            if f.is_file():
                dst = gdir / "runtime" / "3d" / sub / f.relative_to(msrc)
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, dst)


def _copy_3d_assets(gdir, content):
    """Copy any referenced GLB ship models (+ their sibling Textures/) from the
    pirate-kit into the game so 3D models render textured (the colormap lesson).
    Also bundles shared runtime textures (e.g. the water normal map) so the
    three.js Water shader works offline instead of 404ing on a CDN."""
    # Shared runtime textures (water normals, etc.) ride alongside the 3D runtime.
    tex_dir = RUNTIME / "3d" / "textures"
    if tex_dir.is_dir():
        dst_tex = gdir / "runtime" / "3d" / "textures"
        dst_tex.mkdir(parents=True, exist_ok=True)
        for f in tex_dir.iterdir():
            if f.is_file():
                shutil.copy2(f, dst_tex / f.name)
    models = content.get("ship_models", {})
    copied_texture = False
    for rel in set(models.values()):
        dst = gdir / rel  # e.g. assets/ship-large.glb
        src = PIRATE_KIT / Path(rel).name
        if src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            if not copied_texture:
                tex_src = PIRATE_KIT / "Textures" / "colormap.png"
                if tex_src.exists():
                    tex_dst = dst.parent / "Textures" / "colormap.png"
                    tex_dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(tex_src, tex_dst)
                    copied_texture = True
        else:
            print(f"[build_order] WARN ship model not found in pirate-kit: {src.name}")


def _copy_creature_assets(gdir, content):
    """Bundle creature GLBs from the unified library (CREATURES_INDEX.json) for any
    game that requests them, and preserve CC-BY attribution. This is how the 1,555-
    model creature library is wired INTO the build pipeline.

    Request forms in content:
      * content['ocean_life'] = { slot: { model, file?, ... } }   (naval games)
          `model` is the in-game path (e.g. assets/creatures/shark.glb). If a library
          `file` (rel to 3d-models/) is given, copy it to `model`; otherwise keep an
          already-present file.
      * content['creatures'] = { slot: { dest?, file? | type/license/name } }  (generic)
          Resolve a query against the library, copy to `dest`, and write the resolved
          {model, source, license, attribution} back into the slot.

    Naval / battleship 3D games with NO ocean_life get a DEFAULT ocean set
    auto-provisioned (real CC0 sea life + a flying seagull). Missing library binaries
    (gitignored / not downloaded on a fresh checkout) degrade gracefully: a warning
    prints and that creature is skipped — the game still builds.
    """
    try:
        if str(ENGINE) not in sys.path:
            sys.path.insert(0, str(ENGINE))
        import creature_library as CL
    except Exception as e:
        print(f"[build_order] WARN creature_library unavailable ({e}); skipping creatures")
        return

    credits = content.setdefault("credits", {})
    cred_list = credits.setdefault("creatures", [])

    def _credit(entry):
        line = CL.attribution_line(entry)
        if line and line not in cred_list:
            cred_list.append(line)

    # Auto-provision default ocean life for naval games that didn't specify any.
    if content.get("genre") in ("battleship", "navalfree") and not content.get("ocean_life"):
        content["ocean_life"] = json.loads(json.dumps(CL.DEFAULT_OCEAN_LIFE))
        print("[build_order] auto-provisioned default ocean_life (gull/dolphin/shark/whale/manta)")

    # ocean_life slots — copy each referenced library model into the game
    for slot, cfg in (content.get("ocean_life") or {}).items():
        if not isinstance(cfg, dict):
            continue
        model = cfg.get("model") or cfg.get("dest")
        if not model:
            continue
        cfg["model"] = model
        lib_file = cfg.get("file")
        dst = gdir / model
        if lib_file:
            entry = CL.find(lib_file)
            if CL.bundle(lib_file, dst):
                if entry:
                    cfg.setdefault("source", entry.get("source"))
                    cfg.setdefault("license", entry.get("license_class"))
                    _credit(entry)
            else:
                print(f"[build_order] WARN creature model missing in library: {lib_file} (game still builds)")
        elif not dst.exists():
            print(f"[build_order] WARN ocean_life '{slot}' has no library file and none bundled: {model}")

    # generic creatures slots — resolve a query, copy, write resolved metadata back
    for slot, req in (content.get("creatures") or {}).items():
        if not isinstance(req, dict):
            continue
        dest = req.get("dest") or f"assets/creatures/{slot}.glb"
        if req.get("file"):
            entry = CL.find(req["file"]) or {"file": req["file"]}
        else:
            picks = CL.pick(n=1, seed=req.get("seed", slot), type=req.get("type"),
                            license_class=req.get("license"), name_contains=req.get("name"))
            entry = picks[0] if picks else None
        if not entry:
            print(f"[build_order] WARN no creature match for '{slot}' ({req})")
            continue
        if CL.bundle(entry, gdir / dest):
            req["model"] = dest
            req["source"] = entry.get("source")
            req["license"] = entry.get("license_class")
            req["attribution"] = entry.get("attribution")
            _credit(entry)
        else:
            print(f"[build_order] WARN creature binary absent for '{slot}': {entry.get('file')}")

    # keep content tidy: drop empty credit scaffolding when nothing CC-BY was used
    if not cred_list:
        credits.pop("creatures", None)
        if not credits:
            content.pop("credits", None)


def _index_html_2d(content, prof):
    # Ensure the shell loads right after the kernel for every 2D game.
    runtime = list(prof["runtime"])
    if "ffg_shell.js" not in runtime:
        k = runtime.index("ffg_kernel.js") + 1 if "ffg_kernel.js" in runtime else 0
        runtime.insert(k, "ffg_shell.js")
    tags = []
    for rel in runtime:
        if rel == "ffg_loader.js":
            continue
        tags.append(f'<script src="runtime/{rel}"></script>')
    scripts = "\n".join(tags)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{content.get('title','FFG Game')} — ForgeFlow Games</title>
<style>*{{margin:0;padding:0;box-sizing:border-box}}html,body{{width:100%;height:100%;overflow:hidden;background:#0a0e1a}}#game-container{{width:100%;height:100%;display:flex;align-items:center;justify-content:center}}</style>
<script src="https://cdn.jsdelivr.net/npm/phaser@3.90.0/dist/phaser.min.js"></script>
</head><body>
<div id="game-container"></div>
<script>window.GAME_CONFIG=window.GAME_CONFIG||{{hide_bug_button:true}};</script>
<script src="game_controls.js?v=1"></script>
{scripts}
<script>
fetch("content.json").then(function(r){{return r.json()}}).then(function(c){{window.FFG_CONTENT=c}})
 .finally(function(){{var s=document.createElement("script");s.src="runtime/ffg_loader.js?v="+Date.now();document.body.appendChild(s)}});
</script>
</body></html>
"""


def _index_html_3d(content, prof=None):
    # Pick the genre's ESM boot entry from its runtime list (the *boot3d* file) so
    # tactics3d boots via ffg_boot3d_tactics.js, battleship via ffg_boot3d.js, etc.
    boot = "ffg_boot3d.js"
    if prof:
        for rel in prof.get("runtime", []):
            if "boot3d" in rel:
                boot = Path(rel).name
                break
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{content.get('title','FFG Game')} — ForgeFlow Games</title>
<style>*{{margin:0;padding:0;box-sizing:border-box}}html,body{{width:100%;height:100%;overflow:hidden;background:#0a1622}}#game-container{{width:100%;height:100%;position:relative}}canvas{{display:block}}</style>
<script type="importmap">
{{ "imports": {{ "three": "https://cdn.jsdelivr.net/npm/three@0.172.0/build/three.module.js", "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.172.0/examples/jsm/", "cannon-es": "https://cdn.jsdelivr.net/npm/cannon-es@0.20.0/dist/cannon-es.js" }} }}
</script>
</head><body>
<div id="game-container"></div>
<script>window.GAME_CONFIG=window.GAME_CONFIG||{{hide_bug_button:true}};</script>
<script src="game_controls.js?v=1"></script>
<script type="module" src="runtime/3d/{boot}?v={int(__import__('time').time())}"></script>
</body></html>
"""


# ── Flows ─────────────────────────────────────────────────────────────────────
def dry_run(content_path):
    content = json.loads(Path(content_path).read_text(encoding="utf-8"))
    genre = content["genre"]
    print(f"[build_order] DRY RUN — genre={genre}, slug={content.get('slug')}")
    ok, cout, sout = gate_content(content_path, genre)
    print(cout); print(sout)
    if not ok:
        print("[build_order] gates FAILED — would feed fixes back to regeneration, not ship.")
        return 1
    gdir = assemble(content["slug"], content)
    # re-gate the assembled copy
    ok2, _, _ = gate_content(gdir / "content.json", genre)
    print(f"[build_order] assembled -> {gdir}")
    print(f"[build_order] post-assemble gates: {'PASS' if ok2 else 'FAIL'}")
    print("[build_order] next (operator): serve + run feel/fidelity:")
    print(f"    python gates/run_gates.py ../../games/{content['slug']} --url http://localhost:8766/games/{content['slug']}/")
    return 0 if ok2 else 1


def main():
    a = sys.argv[1:]
    if not a:
        print(__doc__)
        sys.exit(2)
    if a[0] == "--dry-run":
        sys.exit(dry_run(a[1]))
    if a[0] == "--slice-prompt":
        print(slice_prompt(a[1], a[2] if len(a) > 2 else "make a fun, fair, polished encounter"))
        print("\n--- operator: pipe the above to `claude -p` in cmd.exe (OAuth lock blocks it in-session) ---")
        sys.exit(0)
    if a[0] == "--expand-prompt":
        content = json.loads(Path(a[1]).read_text(encoding="utf-8"))
        print(expand_prompt(content["genre"], content))
        sys.exit(0)
    if a[0] == "--assemble":
        content = json.loads(Path(a[2]).read_text(encoding="utf-8"))
        gdir = assemble(a[1], content)
        print(f"assembled -> {gdir}")
        sys.exit(0)
    print(__doc__)
    sys.exit(2)


if __name__ == "__main__":
    main()
