"""build_order.py — Layer-3 vertical-slice-first build orchestration.

Replaces the old "generate the whole game then check it runs" with:
    select-engine -> SLICE (1 mission, signature mechanic) -> [GATE] ->
    expand content -> [GATE] -> assemble -> (feel/fidelity)

Content is generated by claude -p as a JSON object that must validate against the
genre schema (so the design can't promise mechanics the engine can't express).
The schema + learned rules are injected into the prompt.

`claude -p` cannot run inside an interactive Claude session (OAuth lock, see
CLAUDE.md), so this module is split:
  - assemble(slug, genre, content) and gate runs work fully offline / now.
  - --dry-run <content.json>: assemble + gate an existing (hand-authored) content
    object end-to-end — proves the whole wiring without generation.
  - --slice-prompt / --expand-prompt <design.json>: print the exact claude -p
    prompt the operator (or Task Scheduler) runs to generate content.

Usage:
    python build_order.py --dry-run ../../games/rift-tactics/content.json
    python build_order.py --slice-prompt tactics "Hold the breach"   # prints prompt
    python build_order.py --assemble <slug> <content.json>           # build game folder
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parent
RUNTIME = ENGINE / "runtime"
GAMES = ENGINE.parent.parent / "games"
REGISTRY = json.loads((ENGINE / "registry.json").read_text(encoding="utf-8"))

sys.path.insert(0, str(ENGINE))
import learn  # noqa: E402


def genre_profile(genre):
    g = REGISTRY["genres"].get(genre)
    if not g:
        raise SystemExit(f"[build_order] unknown genre '{genre}'. Known: {list(REGISTRY['genres'])}")
    return g


# ── Prompt construction (the constrained generator) ──────────────────────────
def slice_prompt(genre, brief):
    prof = genre_profile(genre)
    schema = (ENGINE / prof["schema"]).read_text(encoding="utf-8")
    rules = learn.prompt_block(genre)
    return f"""You are generating CONTENT (data, not engine code) for a browser game on the
ForgeFlow v2 engine. Genre: {genre} ({prof['label']}).
Brief: {brief}

Output ONLY a single JSON object that VALIDATES against this schema. Generate just
the FIRST mission (the vertical slice) — one tight, winnable encounter that fully
exercises the signature mechanic: {prof['signature_mechanic']}.
Do not invent fields outside the schema. Use original IP (no trademarked names).

SCHEMA:
{schema}

{rules}

Return only the JSON object."""


def expand_prompt(genre, content):
    prof = genre_profile(genre)
    rules = learn.prompt_block(genre)
    return f"""The vertical slice below passed all gates. Generate 4-6 ADDITIONAL missions of
escalating difficulty for this {genre} game, same schema, same signature mechanic
({prof['signature_mechanic']}). Keep units/cover varied; ensure every mission is
winnable and every unit spawns on a walkable tile.

{rules}

CURRENT CONTENT:
{json.dumps(content, indent=2)}

Return ONLY the full updated JSON object (slice + new missions)."""


def run_claude_p(prompt, timeout=300):
    """Run claude -p (NON-interactive contexts only). Returns parsed JSON or raises."""
    out = subprocess.run(["claude", "-p", prompt], capture_output=True, text=True, timeout=timeout)
    raw = (out.stdout or "").strip()
    s, e = raw.find("{"), raw.rfind("}")
    if s < 0 or e <= s:
        raise RuntimeError("no JSON in claude -p output: " + raw[:300])
    return json.loads(raw[s:e + 1])


# ── Gates ─────────────────────────────────────────────────────────────────────
def gate_content(content_path, genre):
    c = subprocess.run([sys.executable, str(ENGINE / "gates" / "contract_gate.py"), str(content_path)],
                       capture_output=True, text=True)
    s = subprocess.run(["node", str(ENGINE / "gates" / "signature_gate.cjs"), str(content_path), genre],
                       capture_output=True, text=True)
    return (c.returncode == 0 and s.returncode == 0), c.stdout.strip(), s.stdout.strip()


# ── Assemble ──────────────────────────────────────────────────────────────────
def assemble(slug, content):
    """Write the game folder: copy the pinned runtime, write content.json + index.html."""
    genre = content["genre"]
    prof = genre_profile(genre)
    gdir = GAMES / slug
    (gdir / "runtime" / "sim").mkdir(parents=True, exist_ok=True)
    # copy runtime modules this genre needs (+ loader + version)
    needed = set(prof["runtime"]) | {"ffg_loader.js", "VERSION"}
    for rel in sorted(needed):
        src = RUNTIME / rel
        if not src.exists():
            print(f"[build_order] WARN missing runtime file {rel} (genre '{genre}' not built yet)")
            continue
        dst = gdir / "runtime" / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    (gdir / "content.json").write_text(json.dumps(content, indent=2), encoding="utf-8")
    (gdir / "index.html").write_text(_index_html(content, prof), encoding="utf-8")
    return gdir


def _index_html(content, prof):
    tags = []
    for rel in prof["runtime"]:
        if rel == "ffg_loader.js":
            continue
        tags.append(f'<script src="runtime/{rel}"></script>')
    scripts = "\n".join(tags)
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{content.get('title','FFG Game')} — ForgeFlow Games</title>
<style>*{{margin:0;padding:0;box-sizing:border-box}}html,body{{width:100%;height:100%;overflow:hidden;background:#0a0e1a}}#game-container{{width:100%;height:100%;display:flex;align-items:center;justify-content:center}}</style>
<script src="https://cdn.jsdelivr.net/npm/phaser@3.90.0/dist/phaser.min.js"></script>
</head><body>
<div id="game-container"></div>
{scripts}
<script>
fetch("content.json").then(function(r){{return r.json()}}).then(function(c){{window.FFG_CONTENT=c}})
 .finally(function(){{var s=document.createElement("script");s.src="runtime/ffg_loader.js?v="+Date.now();document.body.appendChild(s)}});
</script>
</body></html>
"""


# ── Flows ─────────────────────────────────────────────────────────────────────
def dry_run(content_path):
    content = json.loads(Path(content_path).read_text(encoding="utf-8"))
    genre = content["genre"]
    print(f"[build_order] DRY RUN — genre={genre}, slug={content.get('slug')}")
    ok, cout, sout = gate_content(content_path, genre)
    print(cout); print(sout)
    if not ok:
        print("[build_order] gates FAILED — would feed fixes back to regeneration, not ship.")
        return 1
    gdir = assemble(content["slug"], content)
    # re-gate the assembled copy
    ok2, _, _ = gate_content(gdir / "content.json", genre)
    print(f"[build_order] assembled -> {gdir}")
    print(f"[build_order] post-assemble gates: {'PASS' if ok2 else 'FAIL'}")
    print("[build_order] next (operator): serve + run feel/fidelity:")
    print(f"    python gates/run_gates.py ../../games/{content['slug']} --url http://localhost:8766/games/{content['slug']}/")
    return 0 if ok2 else 1


def main():
    a = sys.argv[1:]
    if not a:
        print(__doc__)
        sys.exit(2)
    if a[0] == "--dry-run":
        sys.exit(dry_run(a[1]))
    if a[0] == "--slice-prompt":
        print(slice_prompt(a[1], a[2] if len(a) > 2 else "make a fun, fair, polished encounter"))
        print("\n--- operator: pipe the above to `claude -p` in cmd.exe (OAuth lock blocks it in-session) ---")
        sys.exit(0)
    if a[0] == "--expand-prompt":
        content = json.loads(Path(a[1]).read_text(encoding="utf-8"))
        print(expand_prompt(content["genre"], content))
        sys.exit(0)
    if a[0] == "--assemble":
        content = json.loads(Path(a[2]).read_text(encoding="utf-8"))
        gdir = assemble(a[1], content)
        print(f"assembled -> {gdir}")
        sys.exit(0)
    print(__doc__)
    sys.exit(2)


if __name__ == "__main__":
    main()
