#!/usr/bin/env python3
"""seed_queue.py — feed the master list into the build queue (the missing link).

`master_list.json` has ~138 pending games but the v2 pipeline only builds from
`build_queue.json`, and NOTHING populated it from the master list. This classifies each
pending master-list game to a registry genre, keeps only those whose genre has a LIVE
runtime (the rest need their engine built first), generates an original-IP slug + a
quality-encoding brief, and appends them to build_queue.json as `pending` (deduped).

Run: python seed_queue.py            # queue all buildable pending games
     python seed_queue.py --top N    # only the N highest-rated
     python seed_queue.py --dry       # show what would queue, write nothing
"""
import json, sys
from pathlib import Path

ENGINE = Path(__file__).resolve().parent
ML = ENGINE.parent / "master_list.json"
QUEUE = ENGINE / "build_queue.json"
REGISTRY = json.loads((ENGINE / "registry.json").read_text(encoding="utf-8"))
GAMES = ENGINE.parent.parent / "games"

LIVE = {g for g, i in REGISTRY["genres"].items() if i.get("status") == "live"}

# master-list sub_genre -> LIVE registry genre. TRUE-FIT ONLY: a game is queued only when its
# sub-genre genuinely matches the engine's signature mechanic (see registry.json). Force-fitting
# a mismatched genre produces a bad game no matter how well it's built — so anything that needs
# its own engine is left for when that runtime ships, NOT crammed into the closest live one.
SUBGENRE_TO_GENRE = {
    # platformer engine = "gravity + jump/coyote/dash + hazard traversal + goal" (2D side-scroller).
    "2d-platformer": "platformer", "precision-platformer": "platformer", "retro-platformer": "platformer",
    "speed-platformer": "platformer", "single-screen-platformer": "platformer",
    "survival-platformer": "platformer", "rage-platformer": "platformer",
    # shmup engine = "scrolling field + bullet patterns + score multiplier".
    "shmup": "shmup", "bullet-hell": "shmup",
    # tactics3d engine = "grid movement + cover hit% + turn phases".
    "turn-based-tactics": "tactics3d", "tactics": "tactics3d", "grid-tactics": "tactics3d",
    # DELIBERATELY UNMAPPED (need their own engine — do not force-fit):
    #   3d-platformer (Mario Galaxy) -> platformer engine is 2D.
    #   maze (Pac-Man), falling-puzzle (Tetris), logic-puzzle, idle/roblox-clicker, sports-arcade
    #     (Tony Hawk / NBA Jam) -> arcade engine is single-screen reflex (Breakout), not these.
    #   twin-stick / on-rails / space-roguelike -> not a scrolling bullet-pattern shmup.
}

# original-IP slug word banks (seeded by id -> deterministic + unique; the real TITLE is
# generated by claude -p, this is just the folder/URL).
ADJ = ["crimson", "neon", "void", "ember", "frost", "umbra", "azure", "solar", "iron", "jade",
       "onyx", "verdant", "scarlet", "cobalt", "amber", "dusk", "lumen", "nova", "rift", "echo"]
NOUN = ["spire", "drift", "vault", "lance", "grove", "circuit", "warden", "reaver", "haven", "pulse",
        "bastion", "current", "relay", "thicket", "summit", "forge", "current", "vector", "shard", "gale"]


def slugify(idx, used):
    a, n = ADJ[idx % len(ADJ)], NOUN[(idx // len(ADJ)) % len(NOUN)]
    base = f"{a}-{n}"
    s, k = base, 2
    while s in used:
        s = f"{base}-{k}"; k += 1
    used.add(s)
    return s


def brief_for(g, genre):
    sig = REGISTRY["genres"].get(genre, {}).get("signature_mechanic", "")
    return (
        f"Original-IP {genre} game (sub-genre: {g.get('sub_genre')}). Capture the core mechanics "
        f"and game-feel of \"{g.get('inspired_by')}\" (critically acclaimed, {g.get('rating')}%) — but with your "
        f"OWN original name, theme, characters and art. Do NOT reference or reuse that title's IP. "
        f"SIGNATURE MECHANIC for this genre: {sig}. "
        f"MUST SHIP COMPLETE: a working menu (title + difficulty + how-to + settings via FFG.Shell), "
        f"the page control bar (fullscreen/mute/pause), a clear win AND lose state, readable HUD, and "
        f"polished feel — it must play start-to-finish with no manual fixes."
    )


def main():
    dry = "--dry" in sys.argv
    reseed = "--reseed" in sys.argv   # drop prior feeder entries first, then re-add (clean replace)
    top = None
    if "--top" in sys.argv:
        try: top = int(sys.argv[sys.argv.index("--top") + 1])
        except Exception: top = None

    ml = json.loads(ML.read_text(encoding="utf-8"))
    q = json.loads(QUEUE.read_text(encoding="utf-8"))
    if reseed:
        before = len(q.get("queue", []))
        q["queue"] = [i for i in q.get("queue", []) if not i.get("master_list_id")]
        print(f"--reseed: dropped {before - len(q['queue'])} prior feeder entries")
    existing = {i["slug"] for i in q.get("queue", [])}
    shipped = {p.name for p in GAMES.iterdir()} if GAMES.exists() else set()
    used = set(existing) | set(shipped)

    cand = []
    for cat, info in ml.get("categories", {}).items():
        for g in info.get("games", []):
            if g.get("status") != "pending":
                continue
            genre = SUBGENRE_TO_GENRE.get(g.get("sub_genre", ""))
            if genre and genre in LIVE:
                cand.append((g, genre, cat))
    cand.sort(key=lambda x: -(x[0].get("rating") or 0))
    if top:
        cand = cand[:top]

    added = []
    for idx, (g, genre, cat) in enumerate(cand):
        slug = slugify(g.get("id", idx), used)
        item = {
            "slug": slug, "genre": genre, "status": "backlog",   # depth-first promotes from backlog
            "brief": brief_for(g, genre),
            "master_list_bucket": cat, "master_list_id": g.get("id"),
            "inspired_by": g.get("inspired_by"), "rating": g.get("rating"),
        }
        q["queue"].append(item)
        added.append((slug, genre, g.get("rating"), g.get("inspired_by")))

    print(f"true-fit buildable (live genre): {len(cand)} | adding {len(added)} to backlog")
    for s, gen, r, ib in added[:60]:
        print(f"  + {s:18} {gen:10} ({r}%, ~{ib})")
    if dry:
        print("\n--dry: nothing written.")
        return 0
    QUEUE.write_text(json.dumps(q, indent=2) + "\n", encoding="utf-8")
    print(f"\nwrote {QUEUE} — backlog now has {len([i for i in q['queue'] if i.get('status')=='backlog'])} games.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
