/** Grid Rush — core constants & content tables */

export const TITLE = 'Grid Rush';
export const LAPS = 3;
export const RIVAL_COUNT = 5;
/** Road half-width — 1.5× original for roomier circuits */
export const TRACK_HALF_WIDTH = 14.25;
export const ITEM_COOLDOWN = 0.35;

export const PHYSICS = {
  maxSpeed: 58,
  accel: 42,
  brake: 55,
  reverseMax: 22,
  reverseAccel: 28,
  steerBase: 2.35,
  steerHighSpeed: 1.15,
  driftSteerMul: 1.55,
  driftGrip: 0.42,
  grip: 0.88,
  drag: 0.92,
  offTrackDrag: 0.55,
  offTrackMax: 28,
  hopForce: 16,
  hopCooldown: 0.55,
  gravity: 48,
  hoverHeight: 1.15,
  turbineMax: 100,
  turbineDrain: 38,
  turbineRegen: 12,
  turbineDriftGain: 18,
  burstMul: 1.45,
  rubberBandBehind: 1.12,
  rubberBandLead: 0.92,
  hazardIFrames: 0.95,
  hazardKnock: 28,
  hazardStun: 0.28,
};

/** Original chassis — not Neon Veil ships, not Mario karts */
export const VEHICLES = {
  prism: {
    id: 'prism',
    name: 'PRISM SLED',
    blurb: 'Balanced hover sled — clean lines, reliable grip.',
    color: 0x00f0ff,
    accent: 0xff2bd6,
    speed: 1.0,
    accel: 1.05,
    handle: 1.05,
    weight: 1.0,
    shape: 'sled',
  },
  volt: {
    id: 'volt',
    name: 'VOLT RUNNER',
    blurb: 'Top-end thruster bike — slippery, ruthless on straights.',
    color: 0xffe566,
    accent: 0xff6b2b,
    speed: 1.14,
    accel: 0.92,
    handle: 0.88,
    weight: 0.9,
    shape: 'bike',
  },
  phantom: {
    id: 'phantom',
    name: 'GLASS PHANTOM',
    blurb: 'Ultra-light razor chassis — snappy drift, fragile feel.',
    color: 0xaa66ff,
    accent: 0xffffff,
    speed: 0.98,
    accel: 1.12,
    handle: 1.22,
    weight: 0.78,
    shape: 'razor',
  },
  drill: {
    id: 'drill',
    name: 'MAG-DRILL',
    blurb: 'Heavy mag-treads — tanky, resists gadgets, slower turns.',
    color: 0xff6b2b,
    accent: 0x39ff88,
    speed: 0.9,
    accel: 0.95,
    handle: 0.78,
    weight: 1.35,
    shape: 'tank',
  },
  echo: {
    id: 'echo',
    name: 'ECHO WEDGE',
    blurb: 'Angular courier wedge — mid pack specialist.',
    color: 0x39ff88,
    accent: 0x00f0ff,
    speed: 1.04,
    accel: 1.0,
    handle: 1.0,
    weight: 1.05,
    shape: 'wedge',
  },
  nova: {
    id: 'nova',
    name: 'NOVA DISC',
    blurb: 'Spin-stable disc skimmer — wild turbine recovery.',
    color: 0xff2bd6,
    accent: 0xffe566,
    speed: 1.06,
    accel: 1.08,
    handle: 0.95,
    weight: 0.95,
    shape: 'disc',
  },
};

/**
 * Original gadgets — invent names & silhouettes; never banana/shell/star clones.
 * rarity: weight for item roll (higher = more common for trailing racers via scale)
 */
export const ITEMS = {
  pulse_mine: {
    id: 'pulse_mine',
    name: 'PULSE MINE',
    icon: '◆',
    color: '#ff6b2b',
    rarity: 1.1,
    offense: true,
    desc: 'Drops a sticky arc charge on the rail. Detonates on contact.',
  },
  phase_skate: {
    id: 'phase_skate',
    name: 'PHASE SKATE',
    icon: '◇',
    color: '#aa66ff',
    rarity: 0.9,
    offense: false,
    desc: 'Brief phase — pass through hazards + speed slipstream.',
  },
  volt_lash: {
    id: 'volt_lash',
    name: 'VOLT LASH',
    icon: '⚡',
    color: '#ffe566',
    rarity: 1.0,
    offense: true,
    desc: 'Forks lightning at the racer ahead on the circuit.',
  },
  gravity_well: {
    id: 'gravity_well',
    name: 'GRAVITY WELL',
    icon: '◎',
    color: '#00f0ff',
    rarity: 0.85,
    offense: true,
    desc: 'Spawns a pull field that yanks nearby chassis inward.',
  },
  mirror_fog: {
    id: 'mirror_fog',
    name: 'MIRROR FOG',
    icon: '▦',
    color: '#e8f7ff',
    rarity: 0.8,
    offense: true,
    desc: 'Inverts steering for the pilot currently in front of you.',
  },
  overclock: {
    id: 'overclock',
    name: 'OVERCLOCK',
    icon: '▲',
    color: '#39ff88',
    rarity: 1.0,
    offense: false,
    desc: 'Floods turbines for a long sustained burst.',
  },
  emp_bloom: {
    id: 'emp_bloom',
    name: 'EMP BLOOM',
    icon: '✺',
    color: '#ff2bd6',
    rarity: 0.75,
    offense: true,
    desc: 'Radial pulse slows every rival in range.',
  },
  data_siphon: {
    id: 'data_siphon',
    name: 'DATA SIPHON',
    icon: '⇌',
    color: '#66ccff',
    rarity: 0.7,
    offense: true,
    desc: 'Steals the nearest rival’s loaded gadget if they hold one.',
  },
  warp_anchor: {
    id: 'warp_anchor',
    name: 'WARP ANCHOR',
    icon: '⟫',
    color: '#ff88cc',
    rarity: 0.55,
    offense: false,
    desc: 'Snaps you forward along the rail path (short hop).',
  },
  static_veil: {
    id: 'static_veil',
    name: 'STATIC VEIL',
    icon: '⬡',
    color: '#88aaff',
    rarity: 0.95,
    offense: false,
    desc: 'Absorbs one offensive hit; reflects a mild jolt.',
  },
};

export const TRACKS = {
  prism_boulevard: {
    id: 'prism_boulevard',
    name: 'PRISM BOULEVARD',
    blurb: 'Downtown neon ribbon through glass towers.',
    laps: LAPS,
    seed: 101,
    skyTop: 0x0a0618,
    skyBot: 0x4a1238,
    fog: 0x2a0a30,
    ambient: 0x3a2260,
    sun: 0xff7744,
    rail: 0x00f0ff,
    accent: 0xff2bd6,
    radius: 140,
    waves: 2.0,
    heightAmp: 8,
  },
  volt_canyon: {
    id: 'volt_canyon',
    name: 'VOLT CANYON',
    blurb: 'Tight magnetic gorge — punish wide lines.',
    laps: LAPS,
    seed: 202,
    skyTop: 0x081018,
    skyBot: 0x1a3048,
    fog: 0x0a1830,
    ambient: 0x223344,
    sun: 0x88ccff,
    rail: 0xffe566,
    accent: 0xff6b2b,
    radius: 110,
    waves: 3.2,
    heightAmp: 14,
  },
  glass_harbor: {
    id: 'glass_harbor',
    name: 'GLASS HARBOR',
    blurb: 'Wide coastal circuit over reflective fog.',
    laps: LAPS,
    seed: 303,
    skyTop: 0x102038,
    skyBot: 0x88aacc,
    fog: 0x6a90b0,
    ambient: 0x6688aa,
    sun: 0xfff0c8,
    rail: 0x39ff88,
    accent: 0x00f0ff,
    radius: 165,
    waves: 1.4,
    heightAmp: 6,
  },
  null_spire: {
    id: 'null_spire',
    name: 'NULL SPIRE',
    blurb: 'Vertical figure-eight around a dead antenna.',
    laps: LAPS,
    seed: 404,
    skyTop: 0x050510,
    skyBot: 0x220844,
    fog: 0x120820,
    ambient: 0x221133,
    sun: 0xaa66ff,
    rail: 0xaa66ff,
    accent: 0xff2bd6,
    radius: 125,
    waves: 2.6,
    heightAmp: 22,
  },
  echo_yards: {
    id: 'echo_yards',
    name: 'ECHO YARDS',
    blurb: 'Industrial freight loops and cargo ghosts.',
    laps: LAPS,
    seed: 505,
    skyTop: 0x120810,
    skyBot: 0x3a2010,
    fog: 0x281810,
    ambient: 0x332211,
    sun: 0xffaa66,
    rail: 0xff6b2b,
    accent: 0xffe566,
    radius: 150,
    waves: 1.8,
    heightAmp: 10,
  },
};

export const AI_NAMES = [
  'RIX-7',
  'HALO',
  'NYX',
  'QUBIT',
  'SABLE',
  'VEXEL',
  'ORION',
  'LUMEN',
];

export const AI_COLORS = [0xff2bd6, 0xff6b2b, 0x39ff88, 0xffe566, 0xaa66ff, 0x00aaff];
