// VALE UI — token generator (lane UI). _design/tokens.json (the bible's machine-readable half) →
//   src/ui/tokens.ts          typed constants for code (colours, seats, motion, type scale)
//   src/ui/styles/tokens.css  CSS custom properties (+ [data-cvd] relationship palettes, type classes)
//
//   node src/ui/gen_tokens.ts            regenerate both files
//   node src/ui/gen_tokens.ts --check    exit 1 when either file is stale (CI / review)
//
// Naming follows tokens.json meta.cssVars: colors.<key> → --<key>; team.* → --team-<key>;
// fray[n] → --seat-<n>; damage.<key>.color → --dmg-<key>; motion.* → --dur-<key> / --ease-<key>.
// Type sizes are emitted as unitless 1080p pixel numbers (--fs-<name>) and turned into real sizes
// by the type classes: size × --k (the UI scale, styles/base.css), floored at type.floorPx (display
// at its own minPx). Never hand-edit the generated files.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const SRC = join(ROOT, '_design', 'tokens.json');
const OUT_TS = join(HERE, 'tokens.ts');
const OUT_CSS = join(HERE, 'styles', 'tokens.css');

type J = Record<string, any>;
const t: J = JSON.parse(readFileSync(SRC, 'utf8'));

const HEADER = '/* GENERATED by src/ui/gen_tokens.ts from _design/tokens.json — do not edit. */\n';

// ── CSS ─────────────────────────────────────────────────────────────────────────────────────────
const css: string[] = [HEADER, ':root {'];
const v = (name: string, value: string | number): void => { css.push(`  --${name}: ${value};`); };

for (const [k, val] of Object.entries(t.colors as J)) {
  if (typeof val === 'string') v(k, val);
  else if (typeof val === 'number') v(k, String(val));
}
for (const [k, r] of Object.entries(t.colors.rank as J)) v(`rank-${k}`, r.color);
for (const [k, r] of Object.entries(t.colors['item-tier'] as J)) v(`tier-${k}`, r.color);
for (const [k, r] of Object.entries(t.colors.resource as J)) v(`res-${k}`, r.color);
for (const [k, r] of Object.entries(t.colors['terrain-ref'] as J)) v(`terrain-${k}`, r as string);

const team = t.team as J;
for (const k of ['self', 'ally', 'enemy', 'neutral']) v(`team-${k}`, team[k]);
v('team-a', team.a.color);
v('team-b', team.b.color);

for (const s of t.fray as J[]) {
  v(`seat-${s.seat}`, s.color);
  v(`seat-${s.seat}-keyline`, s.keyline === 'chalk' ? 'var(--chalk)' : s.keyline === 'ink' ? 'var(--ink-0)' : 'transparent');
}

const dmg = t.damage as J;
v('dmg-physical', dmg.physical.color);
v('dmg-magic', dmg.magic.color);
v('dmg-true', dmg.true.fill);
v('dmg-true-halo', dmg.true.halo);
v('dmg-heal', dmg.heal.color);
v('dmg-shield', dmg.shield.color);
v('dmg-trail', dmg.trail.color);

const motion = t.motion as J;
for (const [k, ms] of Object.entries(motion.dur as J)) v(`dur-${k}`, `${ms}ms`);
for (const [k, e] of Object.entries(motion.ease as J)) v(`ease-${k}`, e as string);
v('exit-factor', motion.exitFactor);
v('stagger', `${motion.stagger.perItemMs}ms`);
v('stagger-row', `${motion.stagger.gridRowMs}ms`);
v('offset-small', motion.offsetPx.small);
v('offset-panel', motion.offsetPx.panel);
v('modal-scale-from', motion.modalScaleFrom);
v('reduced-fade', `${motion.reducedMotion.fadeMs}ms`);

const type = t.type as J;
const fam = (role: string): string => `'${type[role].family}', 'Vale ${role[0].toUpperCase()}${role.slice(1)} Fallback', ${type.fallback[role]}`;
v('font-display', fam('display'));
v('font-heading', fam('heading'));
v('font-body', fam('body'));
v('font-numeric', fam('numeric'));
v('type-floor', type.floorPx);
v('type-display-floor', type.display.minPx);
for (const [k, s] of Object.entries(type.scale as J)) v(`fs-${k}`, s.px);
css.push('}');

// relationship palettes per colour-vision mode (Settings.access.colorblind → <html data-cvd>)
for (const [mode, pal] of Object.entries(team.colorblind as J)) {
  css.push(`:root[data-cvd="${mode}"] {`);
  for (const k of ['self', 'ally', 'enemy', 'a', 'b']) v(`team-${k}`, (pal as J)[k]);
  css.push('}');
}

// type classes: size × --k, floored; unitless line-height keeps the designed ratio after a floor
css.push('');
for (const [k, s] of Object.entries(type.scale as J)) {
  const role = s.role as string;
  const floor = role === 'display' ? 'var(--type-display-floor)' : 'var(--type-floor)';
  const lines = [
    `  font-family: var(--font-${role});`,
    `  font-size: max(calc(${floor} * 1px), calc(var(--fs-${k}) * var(--k, 1) * 1px));`,
    `  line-height: ${+(s.line / s.px).toFixed(4)};`,
    `  font-weight: ${s.weight};`,
    `  letter-spacing: ${s.trackingEm ?? 0}em;`,
  ];
  if (s.wdth) lines.push(`  font-stretch: ${s.wdth}%;`);
  if (role === 'heading') lines.push('  text-transform: uppercase;');
  if (role === 'numeric') lines.push('  font-variant-numeric: tabular-nums;');
  css.push(`.t-${k} {`, ...lines, '}');
}
const cssText = css.join('\n') + '\n';

// ── TS ──────────────────────────────────────────────────────────────────────────────────────────
const tsData = {
  colors: Object.fromEntries(Object.entries(t.colors as J).filter(([, x]) => typeof x === 'string')),
  rank: t.colors.rank,
  itemTier: t.colors['item-tier'],
  resource: t.colors.resource,
  team: { self: team.self, ally: team.ally, enemy: team.enemy, neutral: team.neutral, a: team.a, b: team.b, names: team.names, shape: team.shape, overrides: team.overrides },
  colorblind: team.colorblind,
  fray: t.fray,
  frayRules: t.frayRules,
  damage: t.damage,
  type: { scale: type.scale, floorPx: type.floorPx, displayMinPx: type.display.minPx, uiScale: type.uiScale, loading: type.loading },
  motion: { dur: motion.dur, ease: motion.ease, exitFactor: motion.exitFactor, stagger: motion.stagger, offsetPx: motion.offsetPx,
    modalScaleFrom: motion.modalScaleFrom, signature: motion.signature, reducedMotion: motion.reducedMotion, menuScene: motion.menuScene },
  hud: { scale: t.hud.scale },
  audioUi: t.audio.ui,
};
const tsText = `// GENERATED by src/ui/gen_tokens.ts from _design/tokens.json — do not edit.\n// The bible's machine-readable half as typed constants for UI code.\n\n`
  + `export const TOKENS = ${JSON.stringify(tsData, null, 2)} as const;\n\n`
  + `export type CvdMode = 'off' | ${Object.keys(team.colorblind).map((k) => `'${k}'`).join(' | ')};\n`
  + `export type FraySeatToken = (typeof TOKENS.fray)[number];\n`
  + `export type TypeRole = keyof typeof TOKENS.type.scale;\n`
  + `export type DurToken = keyof typeof TOKENS.motion.dur;\n`
  + `export type EaseToken = keyof typeof TOKENS.motion.ease;\n`;

const check = process.argv.includes('--check');
let stale = 0;
for (const [file, text] of [[OUT_CSS, cssText], [OUT_TS, tsText]] as const) {
  let cur = '';
  try { cur = readFileSync(file, 'utf8'); } catch { /* missing */ }
  if (cur === text) continue;
  if (check) { stale++; console.error(`stale: ${file}`); } else { writeFileSync(file, text, 'utf8'); console.log(`wrote ${file}`); }
}
if (check) { console.log(stale ? 'tokens: STALE — run node src/ui/gen_tokens.ts' : 'tokens: up to date'); process.exitCode = stale ? 1 : 0; }
