// GENERATED by src/ui/gen_tokens.ts from _design/tokens.json — do not edit.
// The bible's machine-readable half as typed constants for UI code.

export const TOKENS = {
  "colors": {
    "ink-0": "#0B0D11",
    "ink-1": "#11141A",
    "ink-2": "#171B22",
    "ink-3": "#1E232C",
    "ink-4": "#262C37",
    "line-1": "#2C333F",
    "line-2": "#3D4656",
    "text-1": "#EDE6D6",
    "text-2": "#ABA597",
    "text-3": "#8F8A80",
    "text-disabled": "#6E6B66",
    "chalk": "#EDE6D6",
    "chalk-hi": "#FFF8EA",
    "on-chalk": "#0B0D11",
    "catch-light": "rgba(237,230,214,0.06)",
    "edge-shade": "rgba(11,13,17,0.40)",
    "dawnglass-inlay": "#BFD3E6",
    "scrim": "rgba(11,13,17,0.80)",
    "brand-gloam": "#A99BFF",
    "warn": "#F6D04D",
    "ok": "#63D88B",
    "danger": "#FF9A1F",
    "info": "#EDE6D6",
    "bar-plate": "#11141A",
    "keyline": "rgba(0,0,0,0.35)",
    "fog-of-war-tint": "#2A3140"
  },
  "rank": {
    "lamplit": {
      "color": "#8A6248",
      "lstar": 45
    },
    "greylight": {
      "color": "#7D8A9E",
      "lstar": 57
    },
    "rosewake": {
      "color": "#D9897F",
      "lstar": 65
    },
    "clearmorn": {
      "color": "#8FB8E0",
      "lstar": 73
    },
    "highsun": {
      "color": "#E8D39A",
      "lstar": 85
    },
    "noonward": {
      "color": "#F4EEDD",
      "lstar": 94
    },
    "unshadowed": {
      "color": "#FFFFFF",
      "lstar": 100,
      "rim": "prismatic"
    }
  },
  "itemTier": {
    "slate": {
      "color": "#8E96A3",
      "ticks": 1
    },
    "verdigris": {
      "color": "#5FBFA8",
      "ticks": 2
    },
    "gloam": {
      "color": "#A99BFF",
      "ticks": 3
    },
    "noonlit": {
      "color": "#FFF4DA",
      "ticks": 4,
      "glow": true
    }
  },
  "resource": {
    "light": {
      "color": "#8F86F0",
      "model": "pool"
    },
    "tally": {
      "color": "#E8C27A",
      "model": "build"
    },
    "heat": {
      "color": "#D96A4A",
      "model": "heat",
      "hatchDeg": 45
    }
  },
  "team": {
    "self": "#F4EFE2",
    "ally": "#3F9CFF",
    "enemy": "#FF9A1F",
    "neutral": "#A9A49A",
    "a": {
      "name": "Aubade",
      "side": "west",
      "screen": "left",
      "color": "#3F9CFF",
      "glyph": "spire",
      "char": "▲"
    },
    "b": {
      "name": "Serenade",
      "side": "east",
      "screen": "right",
      "color": "#FF9A1F",
      "glyph": "dome",
      "char": "◠"
    },
    "names": {
      "self": "Noonwhite",
      "ally": "Dawn azure",
      "enemy": "Dusk marigold",
      "neutral": "Dialstone"
    },
    "shape": {
      "self": {
        "bar": "double-frame",
        "ring": "solid+gnomon-wedge",
        "minimap": "wedge-arrow"
      },
      "ally": {
        "bar": "rounded-ends",
        "ring": "12-dash",
        "minimap": "round-portrait"
      },
      "enemy": {
        "bar": "chevron-ends",
        "ring": "solid+4-inward-notches",
        "minimap": "round-portrait+heading-wedge"
      },
      "neutral": {
        "bar": "square-ends",
        "ring": "none-until-aggro",
        "minimap": "square"
      }
    },
    "overrides": {
      "self": true,
      "enemy": true,
      "warnBelowDeltaE": 20
    }
  },
  "colorblind": {
    "deutan": {
      "self": "#FBF8F0",
      "ally": "#2FA8FF",
      "enemy": "#FFC21F",
      "a": "#2FA8FF",
      "b": "#FFC21F"
    },
    "protan": {
      "self": "#FBF8F0",
      "ally": "#3F9CFF",
      "enemy": "#FFC21F",
      "a": "#3F9CFF",
      "b": "#FFC21F"
    },
    "tritan": {
      "self": "#FBF8F0",
      "ally": "#2FA8FF",
      "enemy": "#FF3D6E",
      "a": "#2FA8FF",
      "b": "#FF3D6E"
    }
  },
  "fray": [
    {
      "seat": 1,
      "numeral": "I",
      "name": "Crimson",
      "color": "#B2354A",
      "glyph": "disc",
      "char": "●",
      "keyline": "chalk"
    },
    {
      "seat": 2,
      "numeral": "II",
      "name": "Olive",
      "color": "#767305",
      "glyph": "peak",
      "char": "▲",
      "keyline": "chalk"
    },
    {
      "seat": 3,
      "numeral": "III",
      "name": "Lime",
      "color": "#D9FF17",
      "glyph": "ring",
      "char": "○",
      "keyline": "ink"
    },
    {
      "seat": 4,
      "numeral": "IV",
      "name": "Green",
      "color": "#20A04E",
      "glyph": "cross",
      "char": "✚",
      "keyline": "none"
    },
    {
      "seat": 5,
      "numeral": "V",
      "name": "Cyan",
      "color": "#26F3FF",
      "glyph": "block",
      "char": "■",
      "keyline": "ink"
    },
    {
      "seat": 6,
      "numeral": "VI",
      "name": "Blue",
      "color": "#19AFFE",
      "glyph": "sandglass",
      "char": "⧗",
      "keyline": "none"
    },
    {
      "seat": 7,
      "numeral": "VII",
      "name": "Indigo",
      "color": "#7273F5",
      "glyph": "crescent",
      "char": "☾",
      "keyline": "none"
    },
    {
      "seat": 8,
      "numeral": "VIII",
      "name": "Violet",
      "color": "#8121FC",
      "glyph": "saltire",
      "char": "✖",
      "keyline": "chalk"
    },
    {
      "seat": 9,
      "numeral": "IX",
      "name": "Plum",
      "color": "#993F94",
      "glyph": "bar",
      "char": "▬",
      "keyline": "chalk"
    },
    {
      "seat": 10,
      "numeral": "X",
      "name": "Rose",
      "color": "#DC6294",
      "glyph": "lozenge",
      "char": "◆",
      "keyline": "none"
    }
  ],
  "frayRules": {
    "localPlayer": "drawn in team.self (Noonwhite) with own glyph; own seat colour shown as a 2 px line on top of own bar plate and on own Hour Board row",
    "telegraphs": "fill and edge are team.enemy (HARM); caster seat colour + glyph only as a 6 px tick at the origin",
    "stampForward": {
      "glyphScale": 1.5,
      "fillOpacity": 0.6,
      "defaultWhenColorblindModeOn": true
    },
    "simpleColors": "every other seat becomes team.enemy + its glyph",
    "keylinePx": 1
  },
  "damage": {
    "physical": {
      "name": "Chalkstone",
      "color": "#F1E2C6",
      "code": "upright numerals"
    },
    "magic": {
      "name": "Orchid-rose",
      "color": "#FF7BD5",
      "code": "numerals in a 1 px oval chip (tooltips, recap)"
    },
    "true": {
      "name": "Shade",
      "fill": "#101216",
      "halo": "#F4EFE2",
      "haloPx": 2,
      "code": "value-inverted numerals"
    },
    "heal": {
      "name": "Sap",
      "color": "#63D88B",
      "prefix": "+",
      "motion": "rises"
    },
    "shield": {
      "name": "Dawnglass",
      "color": "#DCE8EE",
      "hatchDeg": 45,
      "hatchPx": 1,
      "hatchGapPx": 3
    },
    "trail": {
      "color": "#F4EFE2",
      "holdMs": 150,
      "shrinkMs": 450
    },
    "numbers": {
      "family": "numeric",
      "weight": 700,
      "sizePx": 18,
      "critSizePx": 26,
      "critWeight": 800,
      "outline": {
        "color": "#0B0D11",
        "px": 2,
        "opacity": 0.8
      },
      "risePx": 24,
      "riseMs": 600,
      "fadeMs": 200,
      "mergeMs": 500,
      "maxOnScreen": 8,
      "show": [
        "own outgoing damage on its target",
        "heals you give >= 5% of target max HP"
      ],
      "hide": [
        "incoming damage (shown by the bar trail)",
        "numbers between other players"
      ],
      "spectatorDefault": "off"
    }
  },
  "type": {
    "scale": {
      "display-xl": {
        "role": "display",
        "px": 112,
        "line": 112,
        "weight": 400,
        "trackingEm": 0.02
      },
      "display-l": {
        "role": "display",
        "px": 72,
        "line": 76,
        "weight": 400,
        "trackingEm": 0
      },
      "display-m": {
        "role": "display",
        "px": 44,
        "line": 48,
        "weight": 400,
        "trackingEm": 0
      },
      "h1": {
        "role": "heading",
        "px": 24,
        "line": 28,
        "weight": 650,
        "wdth": 88,
        "trackingEm": 0.06
      },
      "h2": {
        "role": "heading",
        "px": 18,
        "line": 24,
        "weight": 600,
        "wdth": 88,
        "trackingEm": 0.08
      },
      "label": {
        "role": "heading",
        "px": 15,
        "line": 20,
        "weight": 600,
        "wdth": 90,
        "trackingEm": 0.06
      },
      "body-l": {
        "role": "body",
        "px": 18,
        "line": 28,
        "weight": 400,
        "trackingEm": 0
      },
      "body": {
        "role": "body",
        "px": 16,
        "line": 24,
        "weight": 400,
        "trackingEm": 0
      },
      "body-s": {
        "role": "body",
        "px": 14,
        "line": 20,
        "weight": 400,
        "trackingEm": 0.01
      },
      "caption": {
        "role": "body",
        "px": 13,
        "line": 18,
        "weight": 500,
        "trackingEm": 0.02
      },
      "num-gold": {
        "role": "numeric",
        "px": 18,
        "line": 20,
        "weight": 500
      },
      "num-clock": {
        "role": "numeric",
        "px": 20,
        "line": 24,
        "weight": 500
      },
      "num-cooldown": {
        "role": "numeric",
        "px": 22,
        "line": 24,
        "weight": 700
      },
      "overhead-name": {
        "role": "body",
        "px": 12,
        "line": 14,
        "weight": 600,
        "trackingEm": 0.02,
        "outlinePx": 2
      }
    },
    "floorPx": 12,
    "displayMinPx": 28,
    "uiScale": [
      0.8,
      1.5
    ],
    "loading": {
      "preload": [
        "display 400",
        "body 400",
        "body 600",
        "numeric 700"
      ],
      "displayFontDisplay": "block",
      "blockBudgetMs": 300,
      "otherFontDisplay": "swap",
      "sizeAdjustedFallbacks": true
    }
  },
  "motion": {
    "dur": {
      "instant": 60,
      "micro": 100,
      "fast": 160,
      "base": 240,
      "panel": 360,
      "scene": 720,
      "sweep": 900,
      "reward": 1200
    },
    "ease": {
      "dawn": "cubic-bezier(0.16, 1, 0.3, 1)",
      "dusk": "cubic-bezier(0.7, 0, 0.84, 0)",
      "std": "cubic-bezier(0.2, 0, 0, 1)",
      "swing": "cubic-bezier(0.34, 1.4, 0.64, 1)",
      "time": "linear"
    },
    "exitFactor": 0.7,
    "stagger": {
      "perItemMs": 32,
      "capItems": 8,
      "gridRowMs": 48,
      "perLetter": false
    },
    "offsetPx": {
      "small": 16,
      "panel": 32
    },
    "modalScaleFrom": 0.98,
    "signature": {
      "name": "shadow-line wipe",
      "angleDeg": 30,
      "ms": 900,
      "use": "client <-> match only"
    },
    "reducedMotion": {
      "fadeMs": 120,
      "wipe": false,
      "parallax": false,
      "cameraMoves": "cut"
    },
    "menuScene": {
      "idleFpsCapAfterMs": 4000,
      "idleFps": 30,
      "gpuBudgetMs": 3,
      "pauseWhenHidden": true,
      "shadowCreepDegPerMin": 1
    }
  },
  "hud": {
    "scale": {
      "hud": [
        0.75,
        1.25
      ],
      "minimap": [
        0.8,
        1.3
      ]
    }
  },
  "audioUi": {
    "hover": {
      "sound": "dawnglass tink E6",
      "ms": 40,
      "peakDbfs": -32,
      "minIntervalMs": 70
    },
    "press": "escapement tick on pointerdown",
    "confirm": [
      "A5",
      "E6"
    ],
    "back": [
      "E6",
      "A5"
    ],
    "tab": "harp B4",
    "error": "clay double-thud D3",
    "locked": "muffled tick + low glass",
    "purchase": "FM shimmer arpeggio D-F#-A-C#"
  }
} as const;

export type CvdMode = 'off' | 'deutan' | 'protan' | 'tritan';
export type FraySeatToken = (typeof TOKENS.fray)[number];
export type TypeRole = keyof typeof TOKENS.type.scale;
export type DurToken = keyof typeof TOKENS.motion.dur;
export type EaseToken = keyof typeof TOKENS.motion.ease;
