// Sanctum Assault — game data (arenas, classes, abilities, enemies, waves)

export const ARENA_RADIUS = 14;
export const HISCORE_KEY = 'sanctum_assault_hiscore';
export const CAMPAIGN_PROGRESS_KEY = 'sanctum_assault_campaign_best';
export const WAVES_PER_ARENA = 8;
export const HEAL_GOLD_COST = 8;

export const ARENAS = [
  {
    id: 'ember',
    name: 'Ember Crucible',
    emoji: '🔥',
    blurb: 'Cracked volcanic stone, lava seams, rising sparks.',
    floor: 0x3a1810,
    floorAccent: 0xc43c12,
    rim: 0xff6b35,
    rimEmissive: 0xff4400,
    sky: 0x1a0808,
    fog: 0x2a1010,
    ambient: 0xff8844,
    ambientIntensity: 0.55,
    hemiSky: 0xffaa66,
    hemiGround: 0x331100,
    sun: 0xffaa55,
    sunIntensity: 1.15,
    portal: 0xff5522,
    particle: 'sparks',
    modifiers: { fireDuration: 1.15, fireDps: 1.1 },
    clearBanner: 'CRUCIBLE CLEARED!',
  },
  {
    id: 'frost',
    name: 'Frostveil Circle',
    emoji: '❄️',
    blurb: 'Ice tiles, frost veins, pale crystal rim.',
    floor: 0x1a2a38,
    floorAccent: 0x7ec8e3,
    rim: 0xa8e6ff,
    rimEmissive: 0x44aaff,
    sky: 0x0a1520,
    fog: 0x102030,
    ambient: 0x88ccff,
    ambientIntensity: 0.5,
    hemiSky: 0xcceeff,
    hemiGround: 0x112233,
    sun: 0xaaddff,
    sunIntensity: 1.0,
    portal: 0x66ddff,
    particle: 'snow',
    modifiers: { frostDuration: 1.35, frostSlow: 1.15 },
    clearBanner: 'FROSTVEIL SILENCED!',
  },
  {
    id: 'storm',
    name: 'Stormspire Board',
    emoji: '⚡',
    blurb: 'Dark basalt, lightning-inlaid runes, wind.',
    floor: 0x1a1528,
    floorAccent: 0x9b59ff,
    rim: 0xc9a0ff,
    rimEmissive: 0x8844ff,
    sky: 0x0c0818,
    fog: 0x181028,
    ambient: 0xaa88ff,
    ambientIntensity: 0.48,
    hemiSky: 0xddccff,
    hemiGround: 0x1a1028,
    sun: 0xccbbff,
    sunIntensity: 1.05,
    portal: 0xaa66ff,
    particle: 'wind',
    modifiers: { shockDuration: 1.25, shockVfx: 1.4 },
    clearBanner: 'STORM QUIETED!',
  },
  {
    id: 'umbral',
    name: 'Umbral Fen',
    emoji: '🌑',
    blurb: 'Obsidian swamp stone, void cracks, magenta fog.',
    floor: 0x120818,
    floorAccent: 0xc026d3,
    rim: 0xe879f9,
    rimEmissive: 0xaa22cc,
    sky: 0x08040e,
    fog: 0x1a0820,
    ambient: 0xcc66ee,
    ambientIntensity: 0.42,
    hemiSky: 0xeeaaff,
    hemiGround: 0x100818,
    sun: 0xdd88ff,
    sunIntensity: 0.85,
    portal: 0xff44cc,
    particle: 'void',
    modifiers: { enemyVision: 0.95 },
    clearBanner: 'FEN BANISHED!',
  },
  {
    id: 'solar',
    name: 'Solar Bastion',
    emoji: '☀️',
    blurb: 'White-gold marble, sunburst seal, god-rays.',
    floor: 0xd4c4a0,
    floorAccent: 0xf0c14b,
    rim: 0xffe08a,
    rimEmissive: 0xffcc44,
    sky: 0x1a1420,
    fog: 0x2a2030,
    ambient: 0xffe8b0,
    ambientIntensity: 0.7,
    hemiSky: 0xfff5d0,
    hemiGround: 0x443322,
    sun: 0xffeeaa,
    sunIntensity: 1.35,
    portal: 0xffdd66,
    particle: 'gold',
    modifiers: { scoreBonus: 1.1 },
    clearBanner: 'BASTION CLAIMED!',
  },
];

export const CLASSES = {
  warrior: {
    id: 'warrior',
    name: 'Warrior',
    emoji: '⚔',
    blurb: 'Dual weapon kits. Two-Handed power or Sword & Shield control.',
    color: 0xc0392b,
    accent: 0xf0c14b,
    maxHp: 5,
    speed: 6.2,
    dualMode: true,
    modes: {
      twohand: {
        id: 'twohand',
        label: '2H',
        name: 'Two-Handed',
        basic: {
          id: 'heavy_slash',
          name: 'Heavy Slash',
          icon: '⚔',
          cooldown: 0.38,
          damage: 18,
          range: 2.4,
          arc: Math.PI * 0.85,
          knockback: 2.2,
          hitstop: 0.05,
        },
        abilities: [
          {
            id: 'whirlwind',
            name: 'Whirlwind',
            icon: '🌀',
            cooldown: 5.5,
            damage: 12,
            range: 3.2,
            duration: 0.55,
            ticks: 4,
          },
          {
            id: 'ground_slam',
            name: 'Ground Slam',
            icon: '💥',
            cooldown: 7,
            damage: 28,
            range: 3.5,
            knockback: 4,
            hitstop: 0.1,
          },
          {
            id: 'earthsplitter',
            name: 'Earthsplitter',
            icon: '🌋',
            cooldown: 11,
            damage: 40,
            range: 5.5,
            width: 1.6,
            knockback: 3,
          },
        ],
      },
      shield: {
        id: 'shield',
        label: 'S&S',
        name: 'Sword & Shield',
        basic: {
          id: 'sword_strike',
          name: 'Sword Strike',
          icon: '🗡',
          cooldown: 0.28,
          damage: 12,
          range: 2.1,
          arc: Math.PI * 0.7,
          knockback: 1.4,
          hitstop: 0.03,
        },
        abilities: [
          {
            id: 'frontal_swipe',
            name: 'Frontal Swipe',
            icon: '🗡',
            cooldown: 4.5,
            damage: 16,
            range: 2.8,
            arc: Math.PI * 1.1,
            knockback: 2.5,
          },
          {
            id: 'shield_bash',
            name: 'Shield Bash',
            icon: '🛡',
            cooldown: 6,
            damage: 14,
            range: 2.2,
            arc: Math.PI * 0.5,
            knockback: 5,
            status: { type: 'shock', duration: 1.4 },
          },
          {
            id: 'bulwark',
            name: 'Bulwark',
            icon: '🔰',
            cooldown: 12,
            duration: 3.5,
            damageReduce: 0.55,
          },
        ],
        canBlock: true,
      },
    },
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    emoji: '🏹',
    blurb: 'Ranged pressure, fire patches, and area rain.',
    color: 0xe67e22,
    accent: 0xf0c14b,
    maxHp: 4,
    speed: 6.8,
    dualMode: false,
    basic: {
      id: 'single_arrow',
      name: 'Single Arrow',
      icon: '🏹',
      cooldown: 0.32,
      damage: 14,
      projectile: true,
      speed: 28,
      radius: 0.25,
      lifetime: 1.2,
    },
    abilities: [
      {
        id: 'fan_shot',
        name: 'Fan Shot',
        icon: '🎯',
        cooldown: 5,
        damage: 10,
        projectile: true,
        count: 5,
        spread: 0.55,
        speed: 26,
        radius: 0.22,
        lifetime: 1.0,
      },
      {
        id: 'fire_arrow',
        name: 'Fire Arrow',
        icon: '🔥',
        cooldown: 6.5,
        damage: 18,
        projectile: true,
        speed: 24,
        radius: 0.3,
        lifetime: 1.3,
        ground: { type: 'fire', radius: 2.2, duration: 3.5, dps: 8 },
        status: { type: 'burn', duration: 2.5 },
      },
      {
        id: 'rain_of_arrows',
        name: 'Rain of Arrows',
        icon: '🌧',
        cooldown: 12,
        damage: 11,
        aoe: true,
        range: 9,
        radius: 2.8,
        duration: 1.4,
        ticks: 5,
      },
    ],
  },
  mage: {
    id: 'mage',
    name: 'Mage',
    emoji: '✨',
    blurb: 'Arcane bolts, elemental patches, protective ward.',
    color: 0x7b2cbf,
    accent: 0xa8e6ff,
    maxHp: 3,
    speed: 6.0,
    dualMode: false,
    basic: {
      id: 'arcane_bolt',
      name: 'Arcane Bolt',
      icon: '✦',
      cooldown: 0.36,
      damage: 16,
      projectile: true,
      speed: 22,
      radius: 0.32,
      lifetime: 1.4,
      color: 0xc084fc,
    },
    abilities: [
      {
        id: 'fireball',
        name: 'Fireball',
        icon: '🔥',
        cooldown: 5.5,
        damage: 26,
        projectile: true,
        speed: 18,
        radius: 0.45,
        lifetime: 1.5,
        aoeOnHit: 2.4,
        ground: { type: 'fire', radius: 2.5, duration: 3.2, dps: 10 },
        status: { type: 'burn', duration: 2.2 },
        color: 0xff6b35,
      },
      {
        id: 'frost_orb',
        name: 'Frost Orb',
        icon: '❄',
        cooldown: 6,
        damage: 20,
        projectile: true,
        speed: 16,
        radius: 0.4,
        lifetime: 1.6,
        aoeOnHit: 2.2,
        ground: { type: 'frost', radius: 2.6, duration: 4, slow: 0.45 },
        status: { type: 'frost', duration: 2.8, slow: 0.5 },
        color: 0x7ec8e3,
      },
      {
        id: 'arcane_ward',
        name: 'Arcane Ward',
        icon: '🔮',
        cooldown: 14,
        duration: 4,
        damageReduce: 0.65,
        reflect: 0.25,
      },
    ],
  },
};

export const ENEMY_TYPES = {
  grunt: {
    id: 'grunt',
    name: 'Ash Grunt',
    hp: 40,
    speed: 3.4,
    damage: 1,
    attackCd: 1.1,
    attackRange: 1.35,
    radius: 0.55,
    score: 100,
    color: 0x8b4513,
    accent: 0xc0392b,
    scale: 1,
  },
  runner: {
    id: 'runner',
    name: 'Cinder Runner',
    hp: 24,
    speed: 5.6,
    damage: 1,
    attackCd: 0.9,
    attackRange: 1.15,
    radius: 0.42,
    score: 140,
    color: 0xe67e22,
    accent: 0xffcc00,
    scale: 0.85,
  },
  brute: {
    id: 'brute',
    name: 'Basalt Brute',
    hp: 120,
    speed: 2.2,
    damage: 2,
    attackCd: 1.5,
    attackRange: 1.7,
    radius: 0.85,
    score: 280,
    color: 0x4a3728,
    accent: 0x7f8c8d,
    scale: 1.35,
  },
  shaman: {
    id: 'shaman',
    name: 'Void Shaman',
    hp: 55,
    speed: 2.8,
    damage: 1,
    attackCd: 1.8,
    attackRange: 7,
    radius: 0.5,
    score: 220,
    color: 0x5b2c6f,
    accent: 0xe879f9,
    scale: 1.05,
    ranged: true,
    projectileSpeed: 12,
    projectileDamage: 1,
  },
  elite: {
    id: 'elite',
    name: 'Sanctum Elite',
    hp: 200,
    speed: 3.0,
    damage: 2,
    attackCd: 1.2,
    attackRange: 1.6,
    radius: 0.7,
    score: 500,
    color: 0x1a1a2e,
    accent: 0xf0c14b,
    scale: 1.2,
    elite: true,
  },
};

/** Wave compositions per wave index 0..7 within an arena. Arena index scales HP/speed. */
export function getWaveDef(arenaIndex, waveIndex) {
  const a = arenaIndex;
  const w = waveIndex;
  const scale = 1 + a * 0.18 + w * 0.06;
  const packs = [
    [{ type: 'grunt', n: 4 + a }],
    [{ type: 'grunt', n: 3 + a }, { type: 'runner', n: 2 }],
    [{ type: 'grunt', n: 4 }, { type: 'runner', n: 2 + a }, { type: 'shaman', n: 1 }],
    [{ type: 'brute', n: 1 }, { type: 'grunt', n: 4 + a }],
    [{ type: 'runner', n: 4 + a }, { type: 'shaman', n: 2 }],
    [{ type: 'brute', n: 1 + Math.floor(a / 2) }, { type: 'grunt', n: 5 }, { type: 'shaman', n: 1 }],
    [{ type: 'elite', n: 1 }, { type: 'runner', n: 3 }, { type: 'grunt', n: 3 + a }],
    [{ type: 'elite', n: 1 + Math.floor(a / 2) }, { type: 'brute', n: 1 }, { type: 'shaman', n: 2 }, { type: 'runner', n: 3 }],
  ];
  return {
    wave: w + 1,
    total: WAVES_PER_ARENA,
    scale,
    spawns: packs[Math.min(w, packs.length - 1)],
    spawnInterval: Math.max(0.35, 0.85 - a * 0.05 - w * 0.03),
  };
}

export function comboMultiplier(kills) {
  if (kills >= 32) return 32;
  if (kills >= 16) return 16;
  if (kills >= 8) return 8;
  if (kills >= 4) return 4;
  if (kills >= 2) return 2;
  return 1;
}

export function clampToArena(x, z, radius = ARENA_RADIUS - 0.6) {
  const d = Math.hypot(x, z);
  if (d <= radius) return { x, z };
  const s = radius / d;
  return { x: x * s, z: z * s };
}

export function angleDiff(a, b) {
  let d = a - b;
  while (d > Math.PI) d -= Math.PI * 2;
  while (d < -Math.PI) d += Math.PI * 2;
  return d;
}
